import { env } from "cloudflare:workers";
import { getTrainer } from "@/app/auth";
import { getOpenAIConfig } from "@/app/ai-config";

type Source={title:string;url:string;publisher:string};
type StoredSource={name:string;key:string;size:number;type:string;url:string};
type Question={question:string;options:string[];correct:number;explanation:string;objective:string;difficulty:string;sourceIndexes:number[]};
type CourseSection={title:string;content:string;keyPoints:string[];example:string};
type CourseTable={title:string;headers:string[];rows:string[][]};
type CourseDiagram={title:string;steps:string[];caption:string};
type CourseExercise={title:string;instruction:string;expectedAnswer:string};
type GeneratedCourse={title:string;theme:string;duration:number;introduction:string;lesson:{title:string;summary:string;keyPoints:string[];steps:string[];learnerTip:string;hook:string;miniChallenge:string;memoryAid:string;sections:CourseSection[];tables:CourseTable[];diagrams:CourseDiagram[];exercises:CourseExercise[]};questions:Question[];sources:Source[];quality:{score:number;factualConsistency:boolean;noAmbiguity:boolean;levelFit:boolean;cleanFrench:boolean;duplicateFree:boolean;reviewSummary:string}};

const allowedTypes=new Set(["application/pdf","image/png","image/jpeg","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"]);const maxFileBytes=15*1024*1024;const maxTotalBytes=40*1024*1024;const maxFiles=12;const noStore={"Cache-Control":"no-store, max-age=0"};
function toBase64(buffer:ArrayBuffer){const bytes=new Uint8Array(buffer);let binary="";const chunk=0x4000;for(let offset=0;offset<bytes.length;offset+=chunk)binary+=String.fromCharCode(...bytes.subarray(offset,Math.min(offset+chunk,bytes.length)));return btoa(binary)}
function validSource(value:unknown,trainerId:number):value is StoredSource{if(!value||typeof value!=="object")return false;const source=value as StoredSource;return Boolean(source.name&&source.key?.startsWith(`course-sources/${trainerId}/`)&&source.url&&Number.isFinite(source.size)&&source.size>0&&allowedTypes.has(source.type))}
async function errorDetail(response:Response){try{const payload=await response.clone().json() as {error?:{message?:string}};return String(payload.error?.message||"")}catch{return ""}}

export async function POST(request:Request){
  const trainer=await getTrainer(request);if(!trainer)return Response.json({error:"Connexion requise."},{status:401,headers:noStore});
  try{
    const form=await request.formData();const theme=String(form.get("theme")||"").trim();const trainerPrompt=String(form.get("prompt")||"").trim();
    let parsedRefs:unknown[]=[];try{const value=String(form.get("sourceRefs")||"[]");parsedRefs=JSON.parse(value)}catch{return Response.json({error:"La liste des documents est illisible. Sélectionnez-les à nouveau."},{status:400,headers:noStore})}
    const sources=parsedRefs.filter(source=>validSource(source,trainer.id));if(!theme&&!trainerPrompt&&!sources.length)return Response.json({error:"Ajoutez un thème, une consigne ou un document."},{status:400,headers:noStore});if(sources.length>maxFiles)return Response.json({error:`Vous pouvez utiliser jusqu’à ${maxFiles} fichiers.`},{status:400,headers:noStore});const oversized=sources.find(source=>source.size>maxFileBytes);if(oversized)return Response.json({error:`Le fichier « ${oversized.name} » dépasse 15 Mo.`},{status:413,headers:noStore});if(sources.reduce((sum,source)=>sum+source.size,0)>maxTotalBytes)return Response.json({error:"L’ensemble des fichiers dépasse 40 Mo."},{status:413,headers:noStore});
    const validatedAnalysis=String(form.get("validatedAnalysis")||"").trim();if(sources.length&&!validatedAnalysis)return Response.json({error:"Analysez les documents et validez au moins une page, image ou section."},{status:400,headers:noStore});
    const count=Math.min(12,Math.max(3,Number(form.get("count")||8)));const requestedOutputs=form.getAll("outputs").map(String).filter(value=>["course","quiz","activity"].includes(value));const outputs=[...new Set(requestedOutputs.length?requestedOutputs:["course"])];const addOns=form.getAll("addOns").map(String).filter(value=>["exercises","tables","diagrams"].includes(value));const wantsCourse=outputs.includes("course");const wantsQuiz=outputs.includes("quiz");const wantsActivity=outputs.includes("activity");const interactiveCount=wantsQuiz||wantsActivity?count:0;
    const config=await getOpenAIConfig(trainer.id);if(!config)return Response.json({error:"Ajoutez votre clé OpenAI dans Connexions avant de générer le cours."},{status:503,headers:noStore});const models=[...new Set([config.model,"gpt-4.1"])];

    let researchBrief="";let consultedSources:Source[]=[];
    if(form.get("research")==="on"){
      const query=`Recherche des sources sérieuses et récentes pour préparer une formation professionnelle sur : ${theme||trainerPrompt}. Public : ${form.get("audience")||"adultes en formation"}. Objectifs : ${form.get("objective")||"comprendre et appliquer les notions essentielles"}. Priorité absolue aux sites officiels, organismes publics, textes réglementaires, instituts reconnus, universités et organismes professionnels. Croise les affirmations importantes. Retourne une synthèse factuelle en français avec les points utiles au cours.`;
      let researchResponse:Response|null=null;let detail="";
      for(const model of models){researchResponse=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${config.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,tools:[{type:"web_search"}],tool_choice:"required",include:["web_search_call.action.sources"],max_output_tokens:5000,input:query})});if(researchResponse.ok)break;detail=await errorDetail(researchResponse);if([401,429].includes(researchResponse.status))break}
      if(!researchResponse?.ok){const status=researchResponse?.status||502;const message=status===401?"Votre clé OpenAI n’est plus valide. Reconnectez-la dans Connexions.":status===429?"OpenAI signale une limite de quota ou de facturation. Vérifiez votre projet OpenAI.":detail?`La recherche Internet a échoué : ${detail.slice(0,240)}`:"La recherche Internet n’a pas pu être effectuée.";return Response.json({error:message},{status:status===401?401:502,headers:noStore})}
      const researchData=await researchResponse.json() as {output_text?:string;output?:Array<{type?:string;action?:{sources?:Array<{url?:string;title?:string}>};content?:Array<{text?:string}>}>};researchBrief=researchData.output_text||researchData.output?.flatMap(item=>item.content||[]).map(item=>item.text||"").join("")||"";const seen=new Set<string>();consultedSources=(researchData.output||[]).flatMap(item=>item.type==="web_search_call"?(item.action?.sources||[]):[]).filter(item=>Boolean(item.url)&&!seen.has(String(item.url))&&seen.add(String(item.url))).slice(0,10).map(item=>({title:String(item.title||"Source consultée"),url:String(item.url),publisher:"Source vérifiée par la recherche OpenAI"}));if(!researchBrief||!consultedSources.length)return Response.json({error:"La recherche n’a pas trouvé suffisamment de sources vérifiables. Précisez le thème ou décochez temporairement la recherche Internet."},{status:422,headers:noStore})
    }

    const schema={type:"object",additionalProperties:false,properties:{title:{type:"string"},theme:{type:"string"},duration:{type:"integer"},introduction:{type:"string"},lesson:{type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},keyPoints:{type:"array",items:{type:"string"}},steps:{type:"array",items:{type:"string"}},learnerTip:{type:"string"},hook:{type:"string"},miniChallenge:{type:"string"},memoryAid:{type:"string"},sections:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},content:{type:"string"},keyPoints:{type:"array",items:{type:"string"}},example:{type:"string"}},required:["title","content","keyPoints","example"]}},tables:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},headers:{type:"array",items:{type:"string"}},rows:{type:"array",items:{type:"array",items:{type:"string"}}}},required:["title","headers","rows"]}},diagrams:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},steps:{type:"array",items:{type:"string"}},caption:{type:"string"}},required:["title","steps","caption"]}},exercises:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},instruction:{type:"string"},expectedAnswer:{type:"string"}},required:["title","instruction","expectedAnswer"]}}},required:["title","summary","keyPoints","steps","learnerTip","hook","miniChallenge","memoryAid","sections","tables","diagrams","exercises"]},questions:{type:"array",items:{type:"object",additionalProperties:false,properties:{question:{type:"string"},options:{type:"array",items:{type:"string"}},correct:{type:"integer"},explanation:{type:"string"},objective:{type:"string"},difficulty:{type:"string"},sourceIndexes:{type:"array",items:{type:"integer"}}},required:["question","options","correct","explanation","objective","difficulty","sourceIndexes"]}},sources:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},url:{type:"string"},publisher:{type:"string"}},required:["title","url","publisher"]}},quality:{type:"object",additionalProperties:false,properties:{score:{type:"integer"},factualConsistency:{type:"boolean"},noAmbiguity:{type:"boolean"},levelFit:{type:"boolean"},cleanFrench:{type:"boolean"},duplicateFree:{type:"boolean"},reviewSummary:{type:"string"}},required:["score","factualConsistency","noAmbiguity","levelFit","cleanFrench","duplicateFree","reviewSummary"]}},required:["title","theme","duration","introduction","lesson","questions","sources","quality"]};
    const requestedProductions=[wantsCourse?"cours complet":null,wantsQuiz?"quiz corrigé":null,wantsActivity?String(form.get("activityFormat")||"activité de mise en situation"):null].filter(Boolean).join(" + ");const sourceList=consultedSources.map((source,index)=>`${index}: ${source.title} — ${source.url}`).join("\n");const prompt=`Crée un parcours pédagogique complet pour adultes.\nPRODUCTIONS : ${requestedProductions}.\nTHÈME : ${theme||"à déterminer à partir des consignes"}.\nPUBLIC : ${form.get("audience")||"adultes en formation professionnelle"}.\nOBJECTIFS : ${form.get("objective")||"identifier, comprendre et appliquer les notions essentielles"}.\nDURÉE : ${form.get("duration")||60} minutes.\nCONSIGNES : ${trainerPrompt||"français simple, exemples concrets et progression ludique"}.\nCOMPLÉMENTS : ${addOns.join(", ")||"aucun"}.\nVALIDATION DOCUMENTAIRE : ${validatedAnalysis||"aucun document fourni"}.\nSYNTHÈSE DE LA RECHERCHE : ${researchBrief||"recherche Internet non demandée"}.\nSOURCES NUMÉROTÉES :\n${sourceList||"aucune source Internet"}.\n\nRÈGLES : produis ${wantsCourse?"un vrai cours détaillé avec au moins 3 sections, exemples et points clés":"un résumé bref avec sections vides"}. ${interactiveCount?`Produis exactement ${interactiveCount} questions avec 3 ou 4 choix, une seule bonne réponse, une explication et des positions de réponses variées.`:"Retourne questions vide."} ${addOns.includes("exercises")?"Ajoute au moins 2 exercices corrigés.":"Retourne exercises vide."} ${addOns.includes("tables")?"Ajoute au moins un tableau utile.":"Retourne tables vide."} ${addOns.includes("diagrams")?"Ajoute au moins un schéma de processus.":"Retourne diagrams vide."} Utilise uniquement les faits des documents validés et de la synthèse de recherche. Les sourceIndexes correspondent aux numéros de la liste ci-dessus. Retourne sources vide : elles seront ajoutées automatiquement après contrôle.`;
    const content:Array<Record<string,string>>=[];for(let index=0;index<sources.length;index++){const source=sources[index];const object=await env.BUCKET.get(source.key);if(!object)return Response.json({error:`Le fichier « ${source.name} » n’est plus disponible. Sélectionnez-le à nouveau.`},{status:404,headers:noStore});const base64=toBase64(await object.arrayBuffer());content.push({type:"input_text",text:`DOCUMENT ${index+1} — ${source.name}`});if(source.type.startsWith("image/"))content.push({type:"input_image",image_url:`data:${source.type};base64,${base64}`,detail:"high"});else content.push({type:"input_file",filename:source.name,file_data:`data:${source.type};base64,${base64}`})}content.push({type:"input_text",text:prompt});
    let response:Response|null=null;let detail="";for(const model of models){response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${config.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,max_output_tokens:18000,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"complete_training_course",strict:true,schema}}})});if(response.ok)break;detail=await errorDetail(response);if([401,429].includes(response.status))break}
    if(!response?.ok){const status=response?.status||502;const message=status===401?"Votre clé OpenAI n’est plus valide. Reconnectez-la dans Connexions.":status===429?"OpenAI a atteint une limite de quota ou de facturation. Vérifiez votre projet OpenAI.":detail?`La création du cours a échoué : ${detail.slice(0,240)}`:"La création du cours a échoué.";return Response.json({error:message},{status:status===401?401:502,headers:noStore})}
    const data=await response.json() as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};const raw=data.output_text||data.output?.flatMap(item=>item.content||[]).map(item=>item.text||"").join("")||"";if(!raw)return Response.json({error:"OpenAI n’a renvoyé aucun cours exploitable."},{status:422,headers:noStore});const generated=JSON.parse(raw) as GeneratedCourse;generated.sources=consultedSources;
    if(wantsCourse&&(!generated.lesson||!Array.isArray(generated.lesson.sections)||generated.lesson.sections.length<2))return Response.json({error:"Le cours généré est incomplet. Relancez avec un thème ou des objectifs plus précis."},{status:422,headers:noStore});if(addOns.includes("exercises")&&!generated.lesson.exercises?.length)generated.lesson.exercises=[{title:"Mise en application",instruction:`Décrivez comment appliquer les notions essentielles de ${generated.theme||theme} dans une situation professionnelle.`,expectedAnswer:"La réponse doit présenter la situation, la méthode retenue, les précautions et le contrôle final."}];
    const startPosition=Math.floor(Math.random()*4);generated.questions=(interactiveCount?generated.questions||[]:[]).slice(0,count).map((question,index)=>{const options=(question.options||[]).map(String).filter(Boolean).slice(0,4);const correctIndex=Number.isInteger(question.correct)&&question.correct>=0&&question.correct<options.length?question.correct:0;const answer=options[correctIndex];const distractors=options.filter((_,optionIndex)=>optionIndex!==correctIndex);for(let i=distractors.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[distractors[i],distractors[j]]=[distractors[j],distractors[i]]}const target=(startPosition+index)%Math.max(options.length,1);const shuffled=[...distractors];shuffled.splice(target,0,answer);const formatLabel=wantsQuiz&&wantsActivity?(index%2===0?"QUIZ":String(form.get("activityFormat")||"ACTIVITÉ").toUpperCase()):wantsActivity?String(form.get("activityFormat")||"ACTIVITÉ").toUpperCase():"QUIZ";return {...question,objective:`${formatLabel} — ${question.objective||"Vérifier les acquis"}`,options:shuffled,correct:target,sourceIndexes:(question.sourceIndexes||[]).filter(value=>Number.isInteger(value)&&value>=0&&value<consultedSources.length)}}).filter(question=>question.options.length>=3&&question.explanation);if(interactiveCount&&generated.questions.length<3)return Response.json({error:"Le cours a été préparé, mais le quiz ne contient pas assez de questions fiables. Précisez les objectifs puis relancez."},{status:422,headers:noStore});
    const sourceDocuments=sources;generated.questions=generated.questions.map(question=>({...question,sourceIndexes:question.sourceIndexes.map(index=>index+sourceDocuments.length)}));generated.sources=[...sourceDocuments.map(document=>({title:document.name,url:document.url,publisher:document.type==="application/pdf"?"PDF importé":document.type.startsWith("image/")?"Image importée":"Document importé"})),...consultedSources];generated.lesson={...generated.lesson,sourceDocument:sourceDocuments[0],sourceDocuments} as typeof generated.lesson;
    const type=outputs.length>1?(outputs.length===3?"Parcours pédagogique complet":outputs.includes("course")&&outputs.includes("quiz")?"Cours + quiz":outputs.includes("course")?"Cours + activité":"Quiz + activité"):outputs[0]==="course"?"Cours complet":outputs[0]==="quiz"?"Quiz interactif":String(form.get("activityFormat")||"Activité pédagogique");return Response.json({activity:{...generated,type,generationChoices:{outputs,addOns,pdfA4:form.get("pdfA4")==="on"}},mode:sources.length?"openai-documents":"openai-prompt"},{headers:noStore});
  }catch(error){return Response.json({error:error instanceof SyntaxError?"Le cours généré est incomplet. Relancez la création.":error instanceof Error?error.message:"Impossible de générer le cours."},{status:500,headers:noStore})}
}
