import { env } from "cloudflare:workers";
import { getTrainer } from "@/app/auth";
import { getOpenAIConfig } from "@/app/ai-config";

type StoredSource={name:string;key:string;size:number;type:string;url?:string};
const allowedTypes=new Set(["application/pdf","image/png","image/jpeg","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"]);
const maxFileBytes=15*1024*1024;const maxTotalBytes=40*1024*1024;const maxFiles=12;const noStore={"Cache-Control":"no-store, max-age=0"};

function toBase64(buffer:ArrayBuffer){const bytes=new Uint8Array(buffer);let binary="";const chunk=0x4000;for(let offset=0;offset<bytes.length;offset+=chunk)binary+=String.fromCharCode(...bytes.subarray(offset,Math.min(offset+chunk,bytes.length)));return btoa(binary)}
function validSource(value:unknown,trainerId:number):value is StoredSource{if(!value||typeof value!=="object")return false;const source=value as StoredSource;return Boolean(source.name&&source.key?.startsWith(`course-sources/${trainerId}/`)&&Number.isFinite(source.size)&&source.size>0&&allowedTypes.has(source.type))}

export async function POST(request:Request){
  const trainer=await getTrainer(request);if(!trainer)return Response.json({error:"Connexion requise."},{status:401,headers:noStore});
  try{
    const body=await request.json() as {sources?:unknown[]};const sources=(body.sources||[]).filter(source=>validSource(source,trainer.id));
    if(!sources.length)return Response.json({error:"Choisissez au moins un PDF, Word, TXT, PNG ou JPEG à analyser."},{status:400,headers:noStore});
    if(sources.length>maxFiles)return Response.json({error:`Vous pouvez analyser jusqu’à ${maxFiles} fichiers en une fois.`},{status:400,headers:noStore});
    const oversized=sources.find(source=>source.size>maxFileBytes);if(oversized)return Response.json({error:`Le fichier « ${oversized.name} » dépasse 15 Mo.`},{status:413,headers:noStore});
    const totalBytes=sources.reduce((sum,source)=>sum+source.size,0);if(totalBytes>maxTotalBytes)return Response.json({error:"L’ensemble des fichiers dépasse 40 Mo."},{status:413,headers:noStore});
    const config=await getOpenAIConfig(trainer.id);if(!config)return Response.json({error:"Ajoutez votre propre clé OpenAI dans Connexions avant d’utiliser l’analyse des documents."},{status:503,headers:noStore});
    const schema={type:"object",additionalProperties:false,properties:{documentTitle:{type:"string"},pageCount:{type:"integer"},language:{type:"string"},suggestedTheme:{type:"string"},suggestedAudiences:{type:"array",items:{type:"string"}},suggestedObjectives:{type:"array",items:{type:"string"}},pages:{type:"array",items:{type:"object",additionalProperties:false,properties:{sourceIndex:{type:"integer"},sourceName:{type:"string"},sourceType:{type:"string",enum:["pdf","image","document"]},pageNumber:{type:"integer"},title:{type:"string"},summary:{type:"string"},keyPoints:{type:"array",items:{type:"string"}},usable:{type:"boolean"}},required:["sourceIndex","sourceName","sourceType","pageNumber","title","summary","keyPoints","usable"]}},warnings:{type:"array",items:{type:"string"}}},required:["documentTitle","pageCount","language","suggestedTheme","suggestedAudiences","suggestedObjectives","pages","warnings"]};
    const content:Array<Record<string,string>>=[];
    for(let index=0;index<sources.length;index++){const source=sources[index];const object=await env.BUCKET.get(source.key);if(!object)return Response.json({error:`Le fichier « ${source.name} » n’est plus disponible. Sélectionnez-le à nouveau.`},{status:404,headers:noStore});const base64=toBase64(await object.arrayBuffer());content.push({type:"input_text",text:`SOURCE ${index+1} — nom exact : ${source.name}`});if(source.type.startsWith("image/"))content.push({type:"input_image",image_url:`data:${source.type};base64,${base64}`,detail:"high"});else content.push({type:"input_file",filename:source.name,file_data:`data:${source.type};base64,${base64}`})}
    content.push({type:"input_text",text:`Analyse conjointement les ${sources.length} sources pour construire une base pédagogique unique. Lis les textes, tableaux et éléments visuels. Analyse chaque PDF de la première à la dernière page, chaque image comme une page autonome et chaque document Word ou TXT par grande section. Conserve l’ordre des sources. sourceIndex commence à 1 ; pageNumber recommence à 1 pour chaque fichier ; sourceType vaut pdf, image ou document. Pour chaque élément, donne un titre court, un résumé fidèle en français simple, 2 à 5 points importants et indique s’il est pédagogiquement exploitable. Propose ensuite le thème commun, 2 à 4 publics et 3 à 6 objectifs pédagogiques. Signale les contradictions, doublons et passages illisibles.`});
    const models=[...new Set([config.model,"gpt-4.1"])];let response:Response|null=null;let detail="";
    for(const model of models){response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${config.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,max_output_tokens:16000,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"multi_source_training_analysis",strict:true,schema}}})});if(response.ok)break;try{const payload=await response.clone().json() as {error?:{message?:string}};detail=String(payload.error?.message||"")}catch{}if([401,429].includes(response.status))break}
    if(!response?.ok){const status=response?.status||502;const message=status===401?"La connexion OpenAI n’est plus valide. Reconnectez votre clé dans Connexions.":status===429?"OpenAI signale une limite de quota ou de facturation. Vérifiez votre projet OpenAI.":detail?`OpenAI n’a pas pu analyser les fichiers : ${detail.slice(0,240)}`:"L’analyse des documents a échoué. Réessayez dans quelques instants.";return Response.json({error:message},{status:status===401?401:502,headers:noStore})}
    const data=await response.json() as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};const raw=data.output_text||data.output?.flatMap(item=>item.content||[]).map(item=>item.text||"").join("")||"";if(!raw)return Response.json({error:"L’analyse n’a renvoyé aucun résultat."},{status:422,headers:noStore});
    const analysis=JSON.parse(raw) as {pageCount?:number;pages?:Array<{sourceIndex?:number;sourceName?:string;pageNumber?:number}>;warnings?:string[]};if(!Array.isArray(analysis.pages)||!analysis.pages.length)return Response.json({error:"Aucune page, image ou section exploitable n’a été détectée."},{status:422,headers:noStore});
    analysis.pages=analysis.pages.filter((page,index,list)=>Number.isInteger(page.sourceIndex)&&Number(page.sourceIndex)>0&&Number.isInteger(page.pageNumber)&&Number(page.pageNumber)>0&&list.findIndex(candidate=>candidate.sourceIndex===page.sourceIndex&&candidate.pageNumber===page.pageNumber)===index).sort((a,b)=>Number(a.sourceIndex)-Number(b.sourceIndex)||Number(a.pageNumber)-Number(b.pageNumber));analysis.pageCount=analysis.pages.length;analysis.warnings=Array.isArray(analysis.warnings)?analysis.warnings:[];
    const seen=new Set(analysis.pages.map(page=>Number(page.sourceIndex)));sources.forEach((source,index)=>{if(!seen.has(index+1))analysis.warnings!.push(`Aucune fiche n’a été produite pour « ${source.name} ».`)});
    return Response.json({analysis,sources,totalBytes},{headers:noStore});
  }catch(error){return Response.json({error:error instanceof SyntaxError?"Le résultat de l’analyse est incomplet. Réessayez avec moins de pages.":error instanceof Error?error.message:"L’analyse n’a pas pu être terminée."},{status:500,headers:noStore})}
}
