import { env } from 'cloudflare:workers';
import { and,eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { activities,encryptedApiCredentials,learningPathItems,users } from '@/db/schema';
import { AppError,assertSameOrigin,jsonError,jsonOk,readJson } from '@/lib/http';
import { decryptSecret,sha256 } from '@/lib/security';
import { currentParticipant,publicShare } from '@/lib/training-sharing';
import { createVoiceCoachClientSecret } from '@/lib/voice-coach-server';
import { preflightAiUsage,recordAiUsage } from '@/lib/subscriptions-server';

export async function POST(request:Request,context:{params:Promise<{token:string}>}){try{assertSameOrigin(request);const share=await publicShare(decodeURIComponent((await context.params).token));const participant=await currentParticipant(share);if(!participant)throw new AppError(401,'Commencez ou reprenez d’abord votre parcours.','PARTICIPANT_REQUIRED');const owner=(await getDb().select({role:users.role}).from(users).where(eq(users.id,share.trainerId)).limit(1))[0];if(!owner)throw new AppError(404,'Le compte formateur est introuvable.','TRAINER_NOT_FOUND');await preflightAiUsage(share.trainerId,owner.role,'voiceCoach',{voice:true,minimumCredits:2});const body=await readJson(request);const pathItemId=String(body.pathItemId??'').trim();const item=(await getDb().select({activityId:activities.id,contentJson:activities.contentJson}).from(learningPathItems).innerJoin(activities,eq(learningPathItems.activityId,activities.id)).where(and(eq(learningPathItems.id,pathItemId),eq(learningPathItems.pathId,share.pathId),eq(activities.type,'voice-coach'),eq(activities.status,'published'))).limit(1))[0];if(!item)throw new AppError(404,'Cette séance vocale n’appartient pas au parcours.','VOICE_COACH_NOT_FOUND');const credential=(await getDb().select().from(encryptedApiCredentials).where(eq(encryptedApiCredentials.trainerId,share.trainerId)).limit(1))[0];if(!credential)throw new AppError(409,'Le formateur doit connecter sa clé OpenAI avant cette séance.','OPENAI_NOT_CONNECTED');const apiKey=await decryptSecret(credential.ciphertext,credential.iv,env.MASTER_ENCRYPTION_KEY);const safety=await sha256(`participant:${participant.id}:${env.SECURITY_PEPPER}`);const secret=await createVoiceCoachClientSecret(apiKey,JSON.parse(item.contentJson),safety,body.transcriptConsent===true);await recordAiUsage({userId:share.trainerId,feature:'voice_session_started',model:'gpt-realtime-2.1',requestId:`voice-start:${participant.id}:${pathItemId}:${Date.now()}`,status:'started',metadata:{participantId:participant.id}});return jsonOk(secret);}catch(error){return jsonError(error);}}
