import { and, eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { activities, courseFolders, learnerParticipants, learnerProgress, learnerResults, learningPathItems } from '@/db/schema';
import { AppError, assertSameOrigin, jsonError, jsonOk, readJson } from '@/lib/http';
import { currentParticipant, publicShare, splitDisplayName } from '@/lib/training-sharing';

export async function PATCH(request:Request,context:{params:Promise<{token:string}>}){
  try{
    assertSameOrigin(request);const share=await publicShare(decodeURIComponent((await context.params).token));const participant=await currentParticipant(share);if(!participant)throw new AppError(401,'Commencez ou reprenez d’abord votre parcours.','PARTICIPANT_REQUIRED');const body=await readJson(request);const pathItemId=String(body.pathItemId??'').trim();
    const item=(await getDb().select().from(learningPathItems).where(and(eq(learningPathItems.id,pathItemId),eq(learningPathItems.pathId,share.pathId))).limit(1))[0];if(!item)throw new AppError(404,'Cette étape n’appartient pas au parcours.','PATH_ITEM_NOT_FOUND');const activity=(await getDb().select().from(activities).where(eq(activities.id,item.activityId)).limit(1))[0];if(!activity)throw new AppError(404,'Cette activité n’est plus disponible.','ACTIVITY_NOT_FOUND');
    if(share.mode!=='classroom'&&item.unlockAfterPrevious&&item.position>0){const previous=(await getDb().select().from(learningPathItems).where(and(eq(learningPathItems.pathId,share.pathId),eq(learningPathItems.position,item.position-1))).limit(1))[0];if(previous){const state=(await getDb().select().from(learnerProgress).where(and(eq(learnerProgress.participantId,participant.id),eq(learnerProgress.pathItemId,previous.id))).limit(1))[0];const previousPercent=state?.score!=null&&state.maxScore?Math.round(state.score/state.maxScore*100):state?.status==='completed'||state?.status==='passed'?100:0;if(!state||!['completed','passed'].includes(state.status)||previousPercent<previous.minScore)throw new AppError(423,'Terminez d’abord l’étape précédente et atteignez le score demandé.','PATH_ITEM_LOCKED');}}
    const now=Math.floor(Date.now()/1000);const requestedStatus=String(body.status??'in_progress');const existing=(await getDb().select().from(learnerProgress).where(and(eq(learnerProgress.participantId,participant.id),eq(learnerProgress.pathItemId,item.id))).limit(1))[0];const score=Number.isInteger(Number(body.score))?Math.max(0,Number(body.score)):null;const maxScore=Number.isInteger(Number(body.maxScore))&&Number(body.maxScore)>0?Number(body.maxScore):null;const graded=['quiz','audio-quiz','tv-quiz','true-false','drag-drop','matching','scenario','voice-coach'].includes(activity.type);let status:'in_progress'|'completed'|'passed'|'retry'='in_progress';if(requestedStatus!=='in_progress'){if(graded){if(score===null||maxScore===null||score>maxScore)throw new AppError(400,'Le score de cette activité doit être transmis pour terminer l’étape.','SCORE_REQUIRED');status=Math.round(score/maxScore*100)>=item.minScore?'passed':'retry';}else status='completed';}const attempts=status==='in_progress'?(existing?.attempts??0):(existing?.attempts??0)+1;
    await getDb().insert(learnerProgress).values({id:existing?.id??crypto.randomUUID(),participantId:participant.id,pathItemId:item.id,activityId:item.activityId,status,score,maxScore,attempts,durationSeconds:Math.max(0,Math.round(Number(body.durationSeconds)||0)),answersJson:JSON.stringify(Array.isArray(body.answers)?body.answers:[]),startedAt:existing?.startedAt??now,completedAt:status==='in_progress'?null:now,updatedAt:now}).onConflictDoUpdate({target:[learnerProgress.participantId,learnerProgress.pathItemId],set:{status,score,maxScore,attempts,durationSeconds:Math.max(0,Math.round(Number(body.durationSeconds)||0)),answersJson:JSON.stringify(Array.isArray(body.answers)?body.answers:[]),completedAt:status==='in_progress'?null:now,updatedAt:now}});
    const required=share.mode==='classroom'?[item]:await getDb().select().from(learningPathItems).where(and(eq(learningPathItems.pathId,share.pathId),eq(learningPathItems.required,true)));const states=await getDb().select().from(learnerProgress).where(eq(learnerProgress.participantId,participant.id));const completed=required.filter((requiredItem)=>states.some((state)=>state.pathItemId===requiredItem.id&&['completed','passed'].includes(state.status))).length;const progressPercent=required.length?Math.round(completed/required.length*100):100;await getDb().update(learnerParticipants).set({lastPathItemId:item.id,progressPercent,lastSeenAt:now,completedAt:progressPercent===100?now:null}).where(eq(learnerParticipants.id,participant.id));
    if(status!=='in_progress'&&!(activity.type==='external-game'&&(score===null||maxScore===null))){const training=(await getDb().select().from(courseFolders).where(eq(courseFolders.id,share.trainingId)).limit(1))[0];if(training){const names=splitDisplayName(participant.displayName);const finalMax=maxScore??1;const finalScore=Math.min(finalMax,score??finalMax);await getDb().insert(learnerResults).values({id:crypto.randomUUID(),activityId:activity.id,trainerId:share.trainerId,trainingId:share.trainingId,pathId:share.pathId,shareId:share.id,participantId:participant.id,learnerFirstName:names.firstName,learnerLastName:names.lastName,answersJson:JSON.stringify(Array.isArray(body.answers)?body.answers:[]),score:finalScore,maxScore:finalMax,percentage:Math.round(finalScore/finalMax*100),durationSeconds:Math.max(0,Math.round(Number(body.durationSeconds)||0)),attempt:attempts,selfEvaluation:null,createdAt:now});}}
    return jsonOk({progressPercent,lastPathItemId:item.id,status,progress:states,message:progressPercent===100?(share.mode==='classroom'?'Activité terminée. Bravo !':'Parcours terminé. Bravo !'):status==='retry'?'Score enregistré : cette étape est à reprendre.':'Votre progression est enregistrée.'});
  }catch(error){return jsonError(error);}
}
