'use client';
/* eslint-disable @next/next/no-img-element -- les vignettes temporaires proviennent des API officielles des comptes connectés */

import { FormEvent, useCallback, useEffect, useState } from 'react';

type ApiResult<T>={ok:true;data:T}|{ok:false;error:{message:string}};
type Connection={provider:'microsoft'|'google'|'canva';label:string;configured:boolean;connected:boolean;status:string;accountLabel:string;expiresAt:number|null;lastTestedAt:number|null;redirectUri:string;scopes:string[];requiredEnvironment:string[]};
type Resource={id:string;name:string;url:string;category:string;provider:string;resourceType:string;trainingId:string|null;activityId:string|null;placement:string;required:boolean;openMode:string};
type CloudResource={externalId:string;name:string;url:string;resourceType:'presentation'|'document';thumbnailUrl?:string;editUrl?:string;provider:'microsoft'|'google'|'canva';metadata?:Record<string,unknown>};
type Training={id:string;name:string};type Activity={id:string;title:string};
type AiCredentialState={connected:boolean;connectionMode:'personal'|'platform'|'administrator'|'none';credential?:{lastFour:string;model:string}|null;canManagePersonalConnection:boolean};
const linkApps=[['youtube','YouTube','Vidéo, cours ou consigne depuis un lien public.','▶'],['genially','Genially','Présentations et contenus interactifs publiés.','G'],['padlet','Padlet','Murs collaboratifs et ressources de groupe.','P'],['miro','Miro','Tableaux visuels partagés et ateliers.','M'],['kahoot','Kahoot','Jeux et évaluations accessibles par lien.','K'],['learningapps','LearningApps','Exercices interactifs intégrables.','L'],['vimeo','Vimeo','Vidéos pédagogiques et médias hébergés.','V'],['other','Autre application','Tout lien HTTPS ou contenu intégré autorisé.','↗']] as const;

async function request<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const payload=await response.json() as ApiResult<T>;if(!payload.ok)throw new Error(payload.error.message);return payload.data;}

export function ApplicationsConnectionsView({notify}:{notify:(message:string)=>void}){
  const[connections,setConnections]=useState<Connection[]>([]);const[resources,setResources]=useState<Resource[]>([]);const[trainings,setTrainings]=useState<Training[]>([]);const[activities,setActivities]=useState<Activity[]>([]);const[credential,setCredential]=useState<AiCredentialState>({connected:false,connectionMode:'none',canManagePersonalConnection:false});const[apiKey,setApiKey]=useState('');const[model,setModel]=useState('gpt-5.5');const[busy,setBusy]=useState('');const[resourceDialog,setResourceDialog]=useState<{provider:string;cloud?:CloudResource}|null>(null);const[cloudPicker,setCloudPicker]=useState<{provider:Connection['provider'];items:CloudResource[]}|null>(null);
  const load=useCallback(async()=>{try{const[c,r,f,a,k]=await Promise.all([request<{connections:Connection[]}>('/api/connections'),request<{resources:Resource[]}>('/api/resources'),request<{folders:Training[]}>('/api/folders'),request<{activities:Activity[]}>('/api/activities'),request<typeof credential>('/api/credentials')]);setConnections(c.connections);setResources(r.resources);setTrainings(f.folders);setActivities(a.activities);setCredential(k);}catch(reason){notify(reason instanceof Error?reason.message:'Chargement des connexions impossible.');}},[notify]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const connect=async(provider:Connection['provider'])=>{setBusy(provider);try{const result=await request<{authorizationUrl:string}>(`/api/connections/${provider}/start`,{method:'POST'});window.location.assign(result.authorizationUrl);}catch(reason){notify(reason instanceof Error?reason.message:'Connexion impossible.');setBusy('');}};
  const test=async(provider:Connection['provider'])=>{setBusy(provider);try{const result=await request<{message:string}>(`/api/connections/${provider}/test`,{method:'POST'});notify(result.message);await load();}catch(reason){notify(reason instanceof Error?reason.message:'Test impossible.');}finally{setBusy('');}};
  const disconnect=async(provider:Connection['provider'])=>{if(!window.confirm('Déconnecter ce compte ? Les liens déjà enregistrés seront conservés.'))return;setBusy(provider);try{const result=await request<{message:string}>(`/api/connections/${provider}`,{method:'DELETE'});notify(result.message);await load();}catch(reason){notify(reason instanceof Error?reason.message:'Déconnexion impossible.');}finally{setBusy('');}};
  const importCloud=async(provider:Connection['provider'])=>{setBusy(provider);try{const result=await request<{resources:CloudResource[]}>(`/api/connections/${provider}/resources`);setCloudPicker({provider,items:result.resources});if(!result.resources.length)notify('Aucune présentation compatible trouvée dans ce compte.');}catch(reason){notify(reason instanceof Error?reason.message:'Ressources indisponibles.');}finally{setBusy('');}};
  const connectOpenAi=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy('openai');try{const result=await request<{message:string}>('/api/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,model})});setApiKey('');notify(result.message);await load();}catch(reason){notify(reason instanceof Error?reason.message:'Connexion impossible.');}finally{setBusy('');}};
  const saveResource=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!resourceDialog)return;setBusy('resource');const form=new FormData(event.currentTarget);try{const cloud=resourceDialog.cloud;const result=await request<{message:string}>('/api/resources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:cloud?.name??form.get('name'),url:cloud?.url??form.get('url'),provider:cloud?.provider??resourceDialog.provider,resourceType:cloud?.resourceType??form.get('resourceType'),externalId:cloud?.externalId,thumbnailUrl:cloud?.thumbnailUrl,metadata:cloud?.metadata,trainingId:form.get('trainingId')||null,activityId:form.get('activityId')||null,placement:form.get('placement'),required:form.get('required')==='on',openMode:form.get('openMode')})});notify(result.message);setResourceDialog(null);setCloudPicker(null);await load();}catch(reason){notify(reason instanceof Error?reason.message:'Ajout impossible.');}finally{setBusy('');}};
  const sharedAi=credential.connectionMode==='platform'||credential.connectionMode==='administrator';
  return <section className="page-view connections-page"><div className="page-title"><div><p className="overline">Applications et connexions</p><h2>Vos outils, vos comptes, vos ressources.</h2><p>Chaque connexion est isolée par formateur. Aucun mot de passe externe n’est demandé ni conservé.</p></div><button className="button dark" type="button" onClick={()=>setResourceDialog({provider:'other'})}>＋ Ajouter une ressource externe</button></div>
    <div className="connection-security"><span>▣</span><div><strong>Autorisations minimales et jetons chiffrés côté serveur</strong><p>Microsoft, Google et Canva utilisent leur écran officiel d’autorisation. Les autres outils sont ajoutés uniquement par lien public ou intégration autorisée.</p></div></div>
    <div className="application-grid">{connections.map((connection)=><article className="application-card" key={connection.provider}><AppLogo provider={connection.provider}/><div className="application-card-title"><div><h3>{connection.label}</h3><p>{providerCopy(connection.provider)}</p></div><span className={connection.connected?'connected':connection.configured?'ready':'configure'}>{connection.connected?'Connecté':connection.configured?'Prêt à connecter':'À configurer'}</span></div>{connection.connected?<div className="connection-account"><strong>✓ {connection.accountLabel||'Compte connecté'}</strong><small>{connection.lastTestedAt?`Testé le ${new Date(connection.lastTestedAt*1000).toLocaleDateString('fr-FR')}`:'Connexion sécurisée'}</small></div>:!connection.configured?<details className="connection-setup"><summary>Configuration administrateur nécessaire</summary><p>Adresse de redirection :</p><code>{connection.redirectUri}</code><p>Variables protégées :</p><code>{connection.requiredEnvironment.join(' · ')}</code><p>Autorisations : {connection.scopes.join(' · ')}</p></details>:<p className="connection-ready">Votre compte personnel pourra être autorisé sur le site officiel de {connection.label}.</p>}<div className="application-actions">{!connection.connected?<button className="button dark" disabled={!connection.configured||busy===connection.provider} type="button" onClick={()=>void connect(connection.provider)}>{busy===connection.provider?'Ouverture…':'Connecter'}</button>:<><button className="button light" disabled={busy===connection.provider} type="button" onClick={()=>void test(connection.provider)}>Tester la connexion</button><button className="button dark" disabled={busy===connection.provider} type="button" onClick={()=>void importCloud(connection.provider)}>Importer une ressource</button><button className="button light danger-text" type="button" onClick={()=>void disconnect(connection.provider)}>Déconnecter</button></>}</div></article>)}
      {linkApps.map(([provider,label,copy,icon])=><article className="application-card link-mode" key={provider}><span className="application-logo generic">{icon}</span><div className="application-card-title"><div><h3>{label}</h3><p>{copy}</p></div><span className="link">Par lien</span></div><p className="connection-ready">Aucun mot de passe requis. Le lien est vérifié et l’intégration interne n’est proposée que si le fournisseur l’autorise.</p><div className="application-actions"><button className="button dark" type="button" onClick={()=>setResourceDialog({provider})}>Importer une ressource</button></div></article>)}</div>
    <section className="openai-connection"><form onSubmit={connectOpenAi}><div><span>✧</span><div><p className="overline">Intelligence artificielle sécurisée</p><h3>{sharedAi?'Connexion gérée par Progressed Pédago':'Connexion OpenAI'}</h3><p>{sharedAi?'La clé centrale reste exclusivement sur le serveur. Le coach vocal, l’analyse des documents et les générateurs l’utilisent automatiquement, sans transmettre de clé aux formateurs ou aux apprenants.':'Seul l’administrateur peut enregistrer une clé, chiffrée côté serveur et jamais réaffichée.'}</p></div></div>{credential.connected&&<div className="success-banner">✓ {sharedAi?'Connexion serveur active pour les fonctions IA et vocales':`Clé administrateur validée · •••• ${credential.credential?.lastFour??''}`}</div>}{credential.canManagePersonalConnection&&!sharedAi&&<div className="form-row"><label>Clé API administrateur<input type="password" autoComplete="off" value={apiKey} onChange={(event)=>setApiKey(event.target.value)} placeholder="sk-…" required/></label><label>Modèle<input value={model} onChange={(event)=>setModel(event.target.value)}/></label><button className="button dark" disabled={busy==='openai'}>{credential.connectionMode==='personal'?'Remplacer la clé':'Activer la connexion centrale'}</button></div>}</form></section>
    <section className="connected-resource-library"><div className="section-heading"><div><p className="overline">Ressources enregistrées</p><h2>{resources.length} ressource{resources.length>1?'s':''} liée{resources.length>1?'s':''}</h2></div></div>{resources.length?<div className="resource-list enhanced">{resources.map((resource)=><article key={resource.id}><span>{resource.category}</span><div><strong>{resource.name}</strong><small>{resource.trainingId?'Formation associée':'Bibliothèque générale'} · {placementLabel(resource.placement)}</small></div><a href={resource.url} target="_blank" rel="noreferrer">Ouvrir ↗</a><button type="button" onClick={async()=>{if(!window.confirm('Supprimer cette ressource ?'))return;await request(`/api/resources?id=${resource.id}`,{method:'DELETE'});await load();notify('Ressource supprimée.');}}>Supprimer</button></article>)}</div>:<p className="empty-inline">Ajoutez une première ressource depuis une application ou un lien HTTPS.</p>}</section>
    {resourceDialog&&<ResourceDialog selection={resourceDialog} trainings={trainings} activities={activities} busy={busy==='resource'} onClose={()=>setResourceDialog(null)} onSubmit={saveResource}/>} {cloudPicker&&<CloudPicker value={cloudPicker} onClose={()=>setCloudPicker(null)} onChoose={(cloud)=>setResourceDialog({provider:cloud.provider,cloud})}/>} </section>;
}

function ResourceDialog({selection,trainings,activities,busy,onClose,onSubmit}:{selection:{provider:string;cloud?:CloudResource};trainings:Training[];activities:Activity[];busy:boolean;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal-card resource-dialog" onSubmit={onSubmit}><button className="modal-close" type="button" onClick={onClose}>×</button><p className="overline">Ajouter une ressource externe</p><h2>{selection.cloud?selection.cloud.name:'Lien ou contenu publié'}</h2>{!selection.cloud&&<><label>Nom de la ressource<input name="name" required/></label><label>Adresse HTTPS<input name="url" type="url" required placeholder="https://…"/></label><label>Type<select name="resourceType" defaultValue={selection.provider==='youtube'||selection.provider==='vimeo'?'video':'link'}><option value="link">Lien</option><option value="video">Vidéo</option><option value="presentation">Présentation</option><option value="document">Document</option><option value="embed">Contenu intégré</option><option value="download">Téléchargement</option></select></label></>}<div className="form-row two"><label>Formation<select name="trainingId"><option value="">Bibliothèque générale</option>{trainings.map((training)=><option value={training.id} key={training.id}>{training.name}</option>)}</select></label><label>Activité précise<select name="activityId"><option value="">Aucune activité précise</option>{activities.map((activity)=><option value={activity.id} key={activity.id}>{activity.title}</option>)}</select></label></div><div className="form-row"><label>Utilisation<select name="placement"><option value="before">Avant l’exercice</option><option value="after">Après l’exercice</option><option value="course">Comme cours</option><option value="instructions">Comme consigne</option><option value="help">Comme aide</option></select></label><label>Ouverture<select name="openMode"><option value="new_tab">Nouvel onglet</option><option value="site">Dans le site si autorisé</option><option value="download">Téléchargement</option></select></label><label className="check-label"><input name="required" type="checkbox"/>Ressource obligatoire</label></div><div className="modal-actions"><button className="button light" type="button" onClick={onClose}>Annuler</button><button className="button dark" disabled={busy}>{busy?'Enregistrement…':'Ajouter la ressource'}</button></div></form></div>;}
function CloudPicker({value,onClose,onChoose}:{value:{provider:Connection['provider'];items:CloudResource[]};onClose:()=>void;onChoose:(item:CloudResource)=>void}){return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="modal-card cloud-picker"><button className="modal-close" type="button" onClick={onClose}>×</button><p className="overline">Ressources du compte connecté</p><h2>Sélectionner une ressource</h2><div>{value.items.map((item)=><button type="button" onClick={()=>onChoose(item)} key={item.externalId}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span>▣</span>}<div><strong>{item.name}</strong><small>{item.resourceType==='presentation'?'Présentation':'Document'}</small></div><b>Ajouter →</b></button>)}</div></section></div>;}
function AppLogo({provider}:{provider:Connection['provider']}){return <span className={`application-logo ${provider}`}>{provider==='microsoft'?'▦':provider==='google'?'△':'C'}</span>;}
function providerCopy(provider:Connection['provider']){return provider==='microsoft'?'PowerPoint et fichiers OneDrive, en lecture seule.':provider==='google'?'Présentations Google Slides, PPTX et PDF.':'Présentations et créations Canva autorisées.';}
function placementLabel(value:string){return ({before:'Avant l’exercice',after:'Après l’exercice',course:'Cours',instructions:'Consigne',help:'Aide'} as Record<string,string>)[value]??'Ressource';}
