'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityPlayer } from '@/components/activity-player';
import { ACTIVITY_TYPES, type ActivityDraft } from '@/lib/activity-types';
import { COURSE_FOLDER_COLORS, type CourseFolderColor } from '@/lib/course-folders';

type ActivityRecord = ActivityDraft & { id:string;status:'draft'|'published';qualityScore:number;updatedAt:number };
type FolderItem = {activityId:string;position:number};
type CourseFolder = {id:string;name:string;description:string;color:CourseFolderColor;createdAt:number;updatedAt:number;items:FolderItem[]};
type ApiResult<T> = {ok:true;data:T}|{ok:false;error:{message:string}};

const colorLabels: Record<CourseFolderColor,string> = {mint:'Menthe',blue:'Bleu',peach:'Pêche',aqua:'Aqua'};

async function request<T>(url:string,options?:RequestInit):Promise<T> {
  const response = await fetch(url,options); const payload = await response.json() as ApiResult<T>;
  if (!payload.ok) throw new Error(payload.error.message); return payload.data;
}

export function CourseFoldersView({activities,onPlay,notify}:{activities:ActivityRecord[];onPlay:(activity:ActivityRecord)=>void;notify:(message:string)=>void}) {
  const [folders,setFolders] = useState<CourseFolder[]>([]); const [selectedId,setSelectedId] = useState(''); const [editing,setEditing] = useState<CourseFolder|'new'|null>(null); const [managing,setManaging] = useState(false); const [selectedActivities,setSelectedActivities] = useState<string[]>([]); const [journeyIndex,setJourneyIndex] = useState<number|null>(null); const [busy,setBusy] = useState(false);
  const load = useCallback(async () => { try { const data = await request<{folders:CourseFolder[]}>('/api/folders'); setFolders(data.folders); setSelectedId((current) => data.folders.some((folder) => folder.id === current) ? current : data.folders[0]?.id ?? ''); } catch (error) { notify(error instanceof Error ? error.message : 'Chargement des dossiers impossible.'); } },[notify]);
  useEffect(() => { request<{folders:CourseFolder[]}>('/api/folders').then((data) => { setFolders(data.folders); setSelectedId(data.folders[0]?.id ?? ''); }).catch((error) => notify(error instanceof Error ? error.message : 'Chargement des dossiers impossible.')); },[notify]);
  const selected = folders.find((folder) => folder.id === selectedId) ?? null;
  const byId = useMemo(() => new Map(activities.map((activity) => [activity.id,activity])),[activities]);
  const orderedActivities = useMemo(() => (selected?.items ?? []).slice().sort((a,b) => a.position - b.position).map((item) => byId.get(item.activityId)).filter((activity):activity is ActivityRecord => Boolean(activity)),[selected,byId]);
  const startManage = () => { setSelectedActivities(orderedActivities.map((activity) => activity.id)); setManaging(true); };
  const saveItems = async (activityIds:string[]) => { if (!selected) return; setBusy(true); try { const result = await request<{message:string}>(`/api/folders/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({activityIds})}); await load(); setManaging(false); notify(result.message); } catch (error) { notify(error instanceof Error ? error.message : 'Enregistrement impossible.'); } finally { setBusy(false); } };
  const deleteFolder = async (folder:CourseFolder) => { if (!window.confirm(`Supprimer le dossier « ${folder.name} » ? Les activités seront conservées.`)) return; try { const result = await request<{message:string}>(`/api/folders/${folder.id}`,{method:'DELETE'}); await load(); notify(result.message); } catch (error) { notify(error instanceof Error ? error.message : 'Suppression impossible.'); } };
  const move = async (index:number,direction:-1|1) => { const target = index + direction; if (target < 0 || target >= orderedActivities.length) return; const ids = orderedActivities.map((activity) => activity.id); [ids[index],ids[target]] = [ids[target],ids[index]]; await saveItems(ids); };
  const remove = async (activityId:string) => saveItems(orderedActivities.filter((activity) => activity.id !== activityId).map((activity) => activity.id));
  const currentJourneyIndex = journeyIndex ?? 0; const journeyActivity = journeyIndex === null ? null : orderedActivities[currentJourneyIndex] ?? null;

  return <section className="folder-library" aria-labelledby="folders-title">
    <div className="folder-library-heading"><div><p className="overline">Classement thématique</p><h3 id="folders-title">Dossiers et parcours apprenants</h3><p>Regroupez vos activités, puis placez-les dans l’ordre où elles doivent être réalisées.</p></div><button className="button dark" type="button" onClick={() => setEditing('new')}>＋ Nouveau dossier</button></div>
    {folders.length ? <><div className="folder-grid">{folders.map((folder) => { const folderActivities = folder.items.map((item) => byId.get(item.activityId)).filter(Boolean) as ActivityRecord[]; return <button type="button" className={`folder-card ${folder.color} ${selectedId === folder.id ? 'active' : ''}`} onClick={() => { setSelectedId(folder.id); setManaging(false); }} key={folder.id}><span className="folder-tab" aria-hidden="true" /><span className="folder-icon">▰</span><strong>{folder.name}</strong><small>{folderActivities.length} activité{folderActivities.length > 1 ? 's' : ''} · {folderActivities.reduce((sum,activity) => sum + activity.durationMinutes,0)} min</small></button>; })}</div>
      {selected && <article className="folder-detail"><header><div><span className={`folder-dot ${selected.color}`} /><div><p className="overline">Parcours pédagogique</p><h3>{selected.name}</h3><p>{selected.description || 'Ajoutez une description pour préciser l’objectif de ce parcours.'}</p></div></div><div><button className="button light" type="button" onClick={() => setEditing(selected)}>Renommer</button><button className="button light" type="button" onClick={startManage}>Ajouter des activités</button><button className="button dark" type="button" disabled={!orderedActivities.length} onClick={() => setJourneyIndex(0)}>▶ Lancer le parcours</button><button className="icon-danger" type="button" onClick={() => void deleteFolder(selected)} aria-label={`Supprimer le dossier ${selected.name}`}>⌫</button></div></header>
        {managing && <div className="folder-picker"><div><strong>Choisir les activités du dossier</strong><small>Une même activité peut appartenir à plusieurs dossiers.</small></div><div className="folder-picker-list">{activities.map((activity) => <label key={activity.id}><input type="checkbox" checked={selectedActivities.includes(activity.id)} onChange={(event) => setSelectedActivities((items) => event.target.checked ? [...items,activity.id] : items.filter((id) => id !== activity.id))} /><span><strong>{activity.title}</strong><small>{activity.theme} · {activity.durationMinutes} min</small></span></label>)}</div><div className="folder-picker-actions"><button className="button light" type="button" onClick={() => setManaging(false)}>Annuler</button><button className="button dark" type="button" disabled={busy} onClick={() => void saveItems(selectedActivities)}>{busy ? 'Enregistrement…' : 'Enregistrer la sélection'}</button></div></div>}
        {orderedActivities.length ? <ol className="journey-list">{orderedActivities.map((activity,index) => <li key={activity.id}><span className="journey-number">{index + 1}</span><div><small>{ACTIVITY_TYPES.find(([type]) => type === activity.type)?.[1] ?? activity.type}</small><strong>{activity.title}</strong><span>{activity.theme} · {activity.durationMinutes} min</span></div><div><button type="button" disabled={index === 0 || busy} onClick={() => void move(index,-1)} aria-label={`Monter ${activity.title}`}>↑</button><button type="button" disabled={index === orderedActivities.length - 1 || busy} onClick={() => void move(index,1)} aria-label={`Descendre ${activity.title}`}>↓</button><button type="button" onClick={() => onPlay(activity)}>Ouvrir</button><button className="danger" type="button" disabled={busy} onClick={() => void remove(activity.id)}>Retirer</button></div></li>)}</ol> : !managing && <div className="folder-empty"><span>▱</span><strong>Ce dossier est encore vide</strong><p>Ajoutez plusieurs activités pour construire votre premier parcours.</p><button className="button dark" type="button" onClick={startManage}>Ajouter des activités</button></div>}
      </article>}
    </> : <div className="folder-empty"><span>▰</span><strong>Créez votre premier dossier thématique</strong><p>Par exemple : « Sécurité », « Bio-nettoyage » ou « Préparation au CQP ».</p><button className="button dark" type="button" onClick={() => setEditing('new')}>Créer un dossier</button></div>}
    {editing && <FolderDialog folder={editing === 'new' ? null : editing} busy={busy} onClose={() => setEditing(null)} onSave={async (values) => { setBusy(true); try { if (editing === 'new') { const result = await request<{id:string;message:string}>('/api/folders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}); await load(); setSelectedId(result.id); notify(result.message); } else { const result = await request<{message:string}>(`/api/folders/${editing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}); await load(); notify(result.message); } setEditing(null); } catch (error) { notify(error instanceof Error ? error.message : 'Enregistrement impossible.'); } finally { setBusy(false); } }} />}
    {journeyActivity && <ActivityPlayer activity={journeyActivity} onClose={() => setJourneyIndex(null)} journey={{name:selected?.name ?? 'Parcours',index:currentJourneyIndex,total:orderedActivities.length,onPrevious:currentJourneyIndex > 0 ? () => setJourneyIndex(currentJourneyIndex - 1) : undefined,onNext:currentJourneyIndex < orderedActivities.length - 1 ? () => setJourneyIndex(currentJourneyIndex + 1) : undefined}} />}
  </section>;
}

function FolderDialog({folder,busy,onClose,onSave}:{folder:CourseFolder|null;busy:boolean;onClose:()=>void;onSave:(values:{name:string;description:string;color:string})=>Promise<void>}) {
  const submit = (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onSave({name:String(form.get('name') ?? ''),description:String(form.get('description') ?? ''),color:String(form.get('color') ?? 'mint')}); };
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="folder-dialog-title"><form className="modal-card folder-dialog" onSubmit={submit}><button className="modal-close" type="button" onClick={onClose} aria-label="Fermer">×</button><p className="overline">Bibliothèque pédagogique</p><h2 id="folder-dialog-title">{folder ? 'Renommer le dossier' : 'Créer un dossier'}</h2><label>Nom du dossier<input name="name" defaultValue={folder?.name ?? ''} required minLength={2} maxLength={80} placeholder="Ex. Sécurité et prévention" /></label><label>Description du parcours<textarea name="description" defaultValue={folder?.description ?? ''} rows={3} maxLength={280} placeholder="Objectifs, public ou progression prévue" /></label><fieldset><legend>Couleur du dossier</legend><div className="folder-color-options">{COURSE_FOLDER_COLORS.map((color) => <label className={color} key={color}><input type="radio" name="color" value={color} defaultChecked={(folder?.color ?? 'mint') === color} /><span>{colorLabels[color]}</span></label>)}</div></fieldset><div className="modal-actions"><button className="button light" type="button" onClick={onClose}>Annuler</button><button className="button dark" type="submit" disabled={busy}>{busy ? 'Enregistrement…' : folder ? 'Enregistrer' : 'Créer le dossier'}</button></div></form></div>;
}
