'use client';
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { COURSE_IMAGE_PLACEMENT_LABELS, COURSE_IMAGE_PLACEMENTS, COURSE_IMAGE_STYLE_LABELS, COURSE_IMAGE_STYLES, COURSE_IMAGE_WIDTHS, type CourseImage } from '@/lib/course-images';
import type { CoursePage } from '@/lib/course-pages';

type ApiEnvelope<T>={ok:true;data:T}|{ok:false;error:{message:string}};
type LibraryDocument={id:string;originalName:string;mimeType:string;pageCount:number|null;status:string};

export function CourseImageManager({activityId,initialImages,coursePages=[],onClose,onChange}:{activityId:string;initialImages:CourseImage[];coursePages?:CoursePage[];onClose:()=>void;onChange:(images:CourseImage[])=>void}) {
  const [images,setImages]=useState(initialImages); const [selectedId,setSelectedId]=useState(initialImages[0]?.id??''); const [documents,setDocuments]=useState<LibraryDocument[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const selected=useMemo(()=>images.find((image)=>image.id===selectedId)??null,[images,selectedId]);
  useEffect(()=>{apiJson<{files:LibraryDocument[]}>('/api/files').then((result)=>setDocuments(result.files)).catch(()=>setDocuments([]));},[]);

  const commit=(next:CourseImage[],message='')=>{setImages(next);onChange(next);if(message)setNotice(message);};
  const patchSelected=async(values:Record<string,unknown>)=>{if(!selected)return;setBusy(true);setError('');try{const result=await apiJson<{images:CourseImage[];message:string}>(`/api/course-images/${encodeURIComponent(activityId)}/${encodeURIComponent(selected.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});commit(result.images,result.message);}catch(reason){setError(message(reason));}finally{setBusy(false);}};
  const removeSelected=async()=>{if(!selected||!window.confirm('Retirer cette image du cours ?'))return;setBusy(true);setError('');try{const result=await apiJson<{images:CourseImage[];message:string}>(`/api/course-images/${encodeURIComponent(activityId)}/${encodeURIComponent(selected.id)}`,{method:'DELETE'});commit(result.images,result.message);setSelectedId(result.images[0]?.id??'');}catch(reason){setError(message(reason));}finally{setBusy(false);}};
  const regenerate=async()=>{if(!selected)return;setBusy(true);setError('');setNotice('Création d’une nouvelle version…');try{const mode=selected.source==='document'&&selected.sourceFileId?'document-inspired':'ai';const result=await apiJson<{image:CourseImage;message:string}>('/api/course-images',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activityId,mode,placement:selected.placement,pageId:selected.pageId,style:selected.style,prompt:selected.prompt,altText:selected.altText,caption:selected.caption,sourceFileId:selected.sourceFileId,sourcePage:selected.sourcePage,rightsConfirmed:selected.rightsConfirmed,validated:false,replaceImageId:selected.id})});const next=images.map((image)=>image.id===selected.id?result.image:image);commit(next,result.message);}catch(reason){setError(message(reason));}finally{setBusy(false);}};

  return <div className="modal-backdrop image-manager-backdrop" role="dialog" aria-modal="true" aria-labelledby="image-manager-title"><section className="modal-card image-manager-card">
    <button className="modal-close" type="button" onClick={onClose} aria-label="Fermer">×</button><p className="overline">Illustrations du cours</p><h2 id="image-manager-title">Prévisualiser, placer et valider.</h2><p>Seules les images validées apparaissent dans le cours numérique, le plein écran et le PDF A4.</p>
    <div className="image-manager-layout"><aside className="image-manager-list"><strong>{images.length} image{images.length>1?'s':''}</strong>{images.map((image,index)=><button className={image.id===selectedId?'active':''} type="button" onClick={()=>setSelectedId(image.id)} key={image.id}><img src={image.url} alt=""/><span><b>{COURSE_IMAGE_PLACEMENT_LABELS[image.placement]}</b><small>{image.status==='validated'?'Validée ✓':'À valider'} · {index+1}</small></span></button>)}{!images.length&&<p>Aucune image pour le moment.</p>}</aside>
      <main>{selected?<ImageEditor key={selected.id} image={selected} imageCount={images.length} coursePages={coursePages} busy={busy} onSave={patchSelected} onDelete={removeSelected} onRegenerate={regenerate}/>:<div className="image-manager-empty"><span>▧</span><strong>Ajoutez une première image</strong><p>Importez votre visuel, générez-le avec l’IA ou partez d’un document.</p></div>}</main></div>
    <NewCourseImage activityId={activityId} documents={documents} coursePages={coursePages} busy={busy} onBusy={setBusy} onError={setError} onCreated={(image,text)=>{const next=[...images,image];commit(next,text);setSelectedId(image.id);}} />
    {notice&&<div className="form-message" role="status">{notice}</div>}{error&&<div className="form-message error" role="status">{error}</div>}
    <div className="modal-actions"><button className="button dark" type="button" onClick={onClose}>Terminer</button></div>
  </section></div>;
}

function ImageEditor({image,imageCount,coursePages,busy,onSave,onDelete,onRegenerate}:{image:CourseImage;imageCount:number;coursePages:CoursePage[];busy:boolean;onSave:(values:Record<string,unknown>)=>Promise<void>;onDelete:()=>Promise<void>;onRegenerate:()=>Promise<void>}) {
  const [draft,setDraft]=useState(image);
  const save=(event:FormEvent)=>{event.preventDefault();void onSave(draft);};
  return <form className="image-editor" onSubmit={save}><figure className={`course-image-figure width-${draft.width} fit-${draft.fit}`}><img src={image.url} alt={draft.altText} style={{objectPosition:`${draft.focalX}% ${draft.focalY}%`}}/>{draft.caption&&<figcaption>{draft.caption}</figcaption>}</figure><div className="image-editor-status"><span className={draft.status}>{draft.status==='validated'?'Image validée':'Brouillon à vérifier'}</span><small>{draft.source==='ai'?'Générée par l’IA':draft.source==='document'?'Issue d’un document':'Import personnel'}</small></div>
    <div className="form-row"><label>Emplacement<select value={draft.placement} onChange={(event)=>setDraft({...draft,placement:event.target.value as CourseImage['placement']})}>{COURSE_IMAGE_PLACEMENTS.map((value)=><option value={value} key={value}>{COURSE_IMAGE_PLACEMENT_LABELS[value]}</option>)}</select></label>{coursePages.length>0&&<label>Page du cours<select value={draft.pageId??''} onChange={(event)=>setDraft({...draft,pageId:event.target.value||undefined})}><option value="">Choisie automatiquement</option>{coursePages.map((page,index)=><option value={page.id} key={page.id}>{index+1}. {page.title}</option>)}</select></label>}<label>Largeur<select value={draft.width} onChange={(event)=>setDraft({...draft,width:event.target.value as CourseImage['width']})}>{COURSE_IMAGE_WIDTHS.map((value)=><option value={value} key={value}>{value==='small'?'Petite':value==='medium'?'Moyenne':value==='large'?'Grande':'Pleine largeur'}</option>)}</select></label><label>Affichage<select value={draft.fit} onChange={(event)=>setDraft({...draft,fit:event.target.value as CourseImage['fit']})}><option value="contain">Image entière</option><option value="cover">Recadrer</option></select></label></div>
    {draft.fit==='cover'&&<div className="form-row two"><label>Point focal horizontal<input type="range" min="0" max="100" value={draft.focalX} onChange={(event)=>setDraft({...draft,focalX:Number(event.target.value)})}/></label><label>Point focal vertical<input type="range" min="0" max="100" value={draft.focalY} onChange={(event)=>setDraft({...draft,focalY:Number(event.target.value)})}/></label></div>}
    <label>Texte alternatif<input value={draft.altText} onChange={(event)=>setDraft({...draft,altText:event.target.value})}/></label><label>Légende facultative<input value={draft.caption} onChange={(event)=>setDraft({...draft,caption:event.target.value})}/></label><label>Consigne de génération<textarea rows={4} value={draft.prompt} onChange={(event)=>setDraft({...draft,prompt:event.target.value})}/></label>
    <div className="image-editor-actions"><button className="button light" type="button" disabled={busy||image.position===0} onClick={()=>void onSave({position:image.position-1})}>← Plus tôt</button><button className="button light" type="button" disabled={busy||image.position>=imageCount-1} onClick={()=>void onSave({position:image.position+1})}>Plus tard →</button><button className="button light" type="button" disabled={busy} onClick={()=>void onRegenerate()}>✦ Nouvelle version</button><button className="button light danger" type="button" disabled={busy} onClick={()=>void onDelete()}>Supprimer</button><button className="button light" type="button" disabled={busy} onClick={()=>void onSave({status:image.status==='validated'?'draft':'validated'})}>{image.status==='validated'?'Retirer la validation':'Valider l’image ✓'}</button><button className="button dark" disabled={busy}>{busy?'Enregistrement…':'Enregistrer les réglages'}</button></div>
  </form>;
}

function NewCourseImage({activityId,documents,coursePages,busy,onBusy,onError,onCreated}:{activityId:string;documents:LibraryDocument[];coursePages:CoursePage[];busy:boolean;onBusy:(value:boolean)=>void;onError:(value:string)=>void;onCreated:(image:CourseImage,message:string)=>void}) {
  const [open,setOpen]=useState(false); const [mode,setMode]=useState<'upload'|'ai'|'document'>('ai'); const [operation,setOperation]=useState<'document-use'|'document-crop'|'document-inspired'>('document-inspired'); const [file,setFile]=useState<File|null>(null); const [rights,setRights]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();onBusy(true);onError('');const form=new FormData(event.currentTarget);try{let request:RequestInit;if(mode==='upload'){if(!file)throw new Error('Choisissez une image PNG ou JPEG.');const upload=new FormData();upload.set('activityId',activityId);upload.set('mode','upload');upload.set('placement',String(form.get('placement')??'automatic'));upload.set('pageId',String(form.get('pageId')??''));upload.set('style',String(form.get('style')??'automatic'));upload.set('prompt',String(form.get('prompt')??''));upload.set('altText',String(form.get('altText')??''));upload.set('validated','false');upload.set('file',file);request={method:'POST',body:upload};}else{request={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activityId,mode:mode==='ai'?'ai':operation,placement:form.get('placement'),pageId:form.get('pageId'),style:form.get('style'),prompt:form.get('prompt'),altText:form.get('altText'),sourceFileId:form.get('sourceFileId'),sourcePage:Number(form.get('sourcePage')||0),rightsConfirmed:rights,validated:false})};}const result=await apiJson<{image:CourseImage;message:string}>('/api/course-images',request);onCreated(result.image,result.message);setOpen(false);setFile(null);}catch(reason){onError(message(reason));}finally{onBusy(false);}};
  if(!open)return <button className="add-course-image" type="button" onClick={()=>setOpen(true)}>＋ Ajouter ou générer une image</button>;
  return <form className="new-course-image" onSubmit={submit}><header><div><strong>Nouvelle image</strong><small>Elle restera en brouillon jusqu’à votre validation.</small></div><button type="button" onClick={()=>setOpen(false)}>Fermer</button></header><div className="image-source-switch"><button className={mode==='upload'?'active':''} type="button" onClick={()=>setMode('upload')}>↑ Mon image</button><button className={mode==='ai'?'active':''} type="button" onClick={()=>setMode('ai')}>✦ Générer avec l’IA</button><button className={mode==='document'?'active':''} type="button" onClick={()=>setMode('document')}>▤ Depuis un document</button></div>
    {mode==='upload'&&<label className="drop-area">Image PNG ou JPEG<input type="file" accept="image/png,image/jpeg" onChange={(event)=>setFile(event.target.files?.[0]??null)}/><span>{file?.name??'10 Mo maximum'}</span></label>}
    {mode==='document'&&<><div className="form-row two"><label>Document source<select name="sourceFileId" required><option value="">Choisir…</option>{documents.map((document)=><option value={document.id} key={document.id}>{document.originalName}</option>)}</select></label><label>Page à privilégier<input name="sourcePage" type="number" min="1" placeholder="Automatique"/></label></div><div className="document-image-actions"><label><input type="radio" checked={operation==='document-use'} onChange={()=>setOperation('document-use')}/>Utiliser le visuel si j’en possède les droits</label><label><input type="radio" checked={operation==='document-crop'} onChange={()=>setOperation('document-crop')}/>Recadrer le visuel</label><label><input type="radio" checked={operation==='document-inspired'} onChange={()=>setOperation('document-inspired')}/>Créer une illustration originale inspirée</label></div>{operation!=='document-inspired'&&<label className="check-line"><input type="checkbox" checked={rights} onChange={(event)=>setRights(event.target.checked)}/>Je confirme disposer des droits nécessaires pour réutiliser ce visuel.</label>}<p className="copyright-note">Le mode « inspiré » reprend uniquement l’idée pédagogique : la composition et le graphisme sont recréés sans copie exacte.</p></>}
    <div className="form-row"><label>Emplacement<select name="placement" defaultValue="automatic"><option value="automatic">Choisi par l’IA</option>{COURSE_IMAGE_PLACEMENTS.map((value)=><option value={value} key={value}>{COURSE_IMAGE_PLACEMENT_LABELS[value]}</option>)}</select></label>{coursePages.length>0&&<label>Page du cours<select name="pageId" defaultValue=""><option value="">Choisie automatiquement</option>{coursePages.map((page,index)=><option value={page.id} key={page.id}>{index+1}. {page.title}</option>)}</select></label>}<label>Style<select name="style" defaultValue="automatic">{COURSE_IMAGE_STYLES.map((value)=><option value={value} key={value}>{COURSE_IMAGE_STYLE_LABELS[value]}</option>)}</select></label></div><label>Consigne visuelle<textarea name="prompt" rows={3} placeholder="Ex. Montrer clairement les gestes, le matériel et les protections adaptés au public débutant."/></label><label>Texte alternatif<input name="altText" placeholder="Décrivez brièvement ce que montre l’image"/></label><div className="modal-actions"><button className="button light" type="button" onClick={()=>setOpen(false)}>Annuler</button><button className="button dark" disabled={busy}>{busy?'Création en cours…':'Préparer l’image'}</button></div>
  </form>;
}

async function apiJson<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,init);const payload=await response.json() as ApiEnvelope<T>;if(!response.ok||!payload.ok)throw new Error(payload.ok?'La demande a échoué.':payload.error.message);return payload.data;}
function message(reason:unknown){return reason instanceof Error?reason.message:'La modification n’a pas pu être enregistrée.';}
