'use client';

import { DragEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';

type ApiEnvelope<T> = { ok:true;data:T } | { ok:false;error:{message:string} };
type DocumentStatus = 'uploaded'|'validating'|'extracting'|'analyzing'|'indexed'|'ready'|'failed';
type DocumentRecord = {
  id:string;originalName:string;mimeType:string;sizeBytes:number;knowledgeFolderId:string|null;status:DocumentStatus;pageCount:number|null;detectedTheme:string|null;summary:string|null;keywords:string[];errorMessage:string|null;contentCreatedCount:number;analyzedAt:number|null;createdAt:number;
};
type KnowledgeFolder = { id:string;name:string;description:string;createdAt:number;updatedAt:number };
type DocumentPage = { id:string;pageNumber:number;title:string;summary:string;notions:string[];procedures:string[];risks:string[];rules:string[];examples:string[];audiences:string[];objectives:string[];level:string;readingQuality:'good'|'partial'|'illegible';warnings:string[];excludedInformation:string[];selected:boolean;trainerNotes:string;validatedAt:number|null };

export function DocumentLibraryView({ notify }: { notify:(message:string)=>void }) {
  const [documents,setDocuments] = useState<DocumentRecord[]>([]); const [folders,setFolders] = useState<KnowledgeFolder[]>([]); const [activeFolder,setActiveFolder] = useState('all'); const [query,setQuery] = useState(''); const [busy,setBusy] = useState(false); const [progress,setProgress] = useState(''); const [openId,setOpenId] = useState(''); const inputRef = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => {
    try { const [fileData,folderData] = await Promise.all([apiJson<{files:DocumentRecord[]}>('/api/files'),apiJson<{folders:KnowledgeFolder[]}>('/api/documents/folders')]); setDocuments(fileData.files); setFolders(folderData.folders); }
    catch (error) { notify(error instanceof Error ? error.message : 'Chargement de la base documentaire impossible.'); }
  },[notify]);
  useEffect(() => { const timer = window.setTimeout(() => void load(),0); return () => window.clearTimeout(timer); },[load]);
  const filtered = useMemo(() => documents.filter((document) => (activeFolder === 'all' || (activeFolder === 'unfiled' ? !document.knowledgeFolderId : document.knowledgeFolderId === activeFolder)) && `${document.originalName} ${document.detectedTheme ?? ''} ${(document.keywords ?? []).join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())),[documents,activeFolder,query]);

  const upload = async (incoming: File[]) => {
    if (!incoming.length) return;
    setBusy(true); setProgress(`Import sécurisé de ${incoming.length} document(s)…`);
    try {
      const form = new FormData(); incoming.forEach((file) => form.append('files',file));
      const result = await apiJson<{files:Array<{id:string;name:string}>;errors:Array<{name:string;message:string}>;message:string}>('/api/files',{method:'POST',body:form});
      await load();
      if (result.errors.length) notify(result.errors.map((error) => `${error.name} : ${error.message}`).join(' · ')); else notify(result.message);
      for (const [index,file] of result.files.entries()) {
        setProgress(`Analyse page par page : ${file.name} (${index + 1}/${result.files.length})…`);
        try { await apiJson(`/api/documents/${file.id}/analyze`,{method:'POST'}); } catch (error) { notify(error instanceof Error ? `${file.name} a été importé, mais son analyse a échoué : ${error.message}` : `Analyse de ${file.name} impossible.`); }
      }
      await load();
    } catch (error) { notify(error instanceof Error ? error.message : 'Import impossible.'); }
    finally { setBusy(false); setProgress(''); if (inputRef.current) inputRef.current.value = ''; }
  };

  const analyze = async (document: DocumentRecord) => {
    setBusy(true); setProgress(`Analyse visuelle et pédagogique de « ${document.originalName} »…`);
    try { const result = await apiJson<{message:string}>(`/api/documents/${document.id}/analyze`,{method:'POST'}); notify(result.message); await load(); setOpenId(document.id); }
    catch (error) { notify(error instanceof Error ? error.message : 'Analyse impossible.'); await load(); }
    finally { setBusy(false); setProgress(''); }
  };
  const rename = async (document:DocumentRecord) => { const originalName = window.prompt('Nouveau nom du document',document.originalName); if (!originalName || originalName === document.originalName) return; try { await apiJson(`/api/files/${document.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({originalName})}); await load(); notify('Le document a été renommé.'); } catch (error) { notify(error instanceof Error ? error.message : 'Renommage impossible.'); } };
  const move = async (document:DocumentRecord,value:string) => { try { await apiJson(`/api/files/${document.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({knowledgeFolderId:value || null})}); await load(); notify('Le document a été rangé.'); } catch (error) { notify(error instanceof Error ? error.message : 'Déplacement impossible.'); } };
  const remove = async (document:DocumentRecord) => { if (!window.confirm(`Supprimer définitivement « ${document.originalName} » et son analyse ? Les activités déjà créées seront conservées.`)) return; try { await apiJson(`/api/files?id=${encodeURIComponent(document.id)}`,{method:'DELETE'}); if (openId === document.id) setOpenId(''); await load(); notify('Le document a été supprimé de votre base privée.'); } catch (error) { notify(error instanceof Error ? error.message : 'Suppression impossible.'); } };
  const createFolder = async () => { const name = window.prompt('Nom du nouveau dossier documentaire'); if (!name) return; try { await apiJson('/api/documents/folders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}); await load(); notify('Le dossier documentaire a été créé.'); } catch (error) { notify(error instanceof Error ? error.message : 'Création du dossier impossible.'); } };
  const renameFolder = async (folder:KnowledgeFolder) => { const name = window.prompt('Nouveau nom du dossier',folder.name); if (!name || name === folder.name) return; try { await apiJson('/api/documents/folders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...folder,name})}); await load(); notify(`Le dossier s’appelle maintenant « ${name.trim()} ».`); } catch (error) { notify(error instanceof Error ? error.message : 'Renommage impossible.'); } };
  const removeFolder = async (folder:KnowledgeFolder) => { if (!window.confirm(`Supprimer le dossier « ${folder.name} » ? Les documents seront conservés sans dossier.`)) return; try { await apiJson(`/api/documents/folders?id=${encodeURIComponent(folder.id)}`,{method:'DELETE'}); if (activeFolder === folder.id) setActiveFolder('all'); await load(); notify('Le dossier a été supprimé ; les documents sont conservés.'); } catch (error) { notify(error instanceof Error ? error.message : 'Suppression impossible.'); } };
  const drop = (event:DragEvent<HTMLLabelElement>) => { event.preventDefault(); if (!busy) void upload(Array.from(event.dataTransfer.files)); };

  return <section className="page-view document-library-view">
    <div className="page-title"><div><p className="overline">Base documentaire privée</p><h2>Vos sources, analysées page par page.</h2><p>Les documents restent isolés dans votre compte. Vous choisissez ensuite les pages fiables utilisées par l’IA.</p></div><button className="button dark" type="button" onClick={() => inputRef.current?.click()} disabled={busy}>＋ Importer des documents</button></div>
    <div className="document-security-banner"><span>▣</span><div><strong>Stockage privé et réutilisable</strong><p>PDF, Word, PowerPoint, texte et images · validation du format réel · 20 Mo par fichier · aucune bibliothèque partagée entre formateurs.</p></div></div>
    <div className="document-workspace">
      <aside className="knowledge-folders"><header><div><strong>Dossiers</strong><small>{documents.length} document(s)</small></div><button type="button" onClick={createFolder}>＋</button></header><button className={activeFolder === 'all' ? 'active' : ''} type="button" onClick={() => setActiveFolder('all')}><span>▤</span>Tous les documents<b>{documents.length}</b></button><button className={activeFolder === 'unfiled' ? 'active' : ''} type="button" onClick={() => setActiveFolder('unfiled')}><span>□</span>Sans dossier<b>{documents.filter((document) => !document.knowledgeFolderId).length}</b></button>{folders.map((folder) => <div className="knowledge-folder-row" key={folder.id}><button className={activeFolder === folder.id ? 'active' : ''} type="button" onClick={() => setActiveFolder(folder.id)}><span>▥</span>{folder.name}<b>{documents.filter((document) => document.knowledgeFolderId === folder.id).length}</b></button><details><summary>•••</summary><button type="button" onClick={() => renameFolder(folder)}>Renommer</button><button type="button" onClick={() => removeFolder(folder)}>Supprimer</button></details></div>)}</aside>
      <div className="document-main">
        <label className={`document-drop-zone ${busy ? 'busy' : ''}`} onDragOver={(event) => event.preventDefault()} onDrop={drop}><input ref={inputRef} type="file" multiple accept=".pdf,.docx,.ppt,.pptx,.txt,.png,.jpg,.jpeg" onChange={(event) => void upload(Array.from(event.target.files ?? []))} disabled={busy} /><span>⇧</span><div><strong>Déposez vos documents ici</strong><small>Ils seront importés séparément puis analysés automatiquement. L’échec d’un fichier ne supprime pas les autres.</small></div><b>Choisir des fichiers</b></label>
        {progress && <div className="document-progress" role="status"><i /><span>{progress}</span></div>}
        <div className="document-toolbar"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un document, un thème ou un mot-clé" /><span>{filtered.length} résultat(s)</span></div>
        <div className="document-list">{filtered.map((document) => <article className={`knowledge-document-card status-${document.status}`} key={document.id}>
          <button className="document-card-main" type="button" onClick={() => setOpenId((value) => value === document.id ? '' : document.id)}><span className="document-format">{formatIcon(document.mimeType)}</span><div><div className="document-title-line"><h3>{document.originalName}</h3><StatusBadge status={document.status} /></div><p>{document.summary || statusCopy(document.status)}</p><div className="document-meta"><span>{formatBytes(document.sizeBytes)}</span><span>{document.pageCount ? `${document.pageCount} page(s)` : 'Pages à détecter'}</span><span>{new Date(document.createdAt * 1000).toLocaleDateString('fr-FR')}</span><span>{document.contentCreatedCount} contenu(s) créé(s)</span></div>{!!document.keywords?.length && <div className="document-keywords">{document.keywords.slice(0,6).map((keyword) => <span key={keyword}>{keyword}</span>)}</div>}{document.errorMessage && <p className="document-error">{document.errorMessage}</p>}</div><b>{openId === document.id ? '−' : '+'}</b></button>
          <div className="document-actions"><a href={`/api/files/${document.id}?preview=1`} target="_blank" rel="noreferrer">Aperçu</a><a href={`/api/files/${document.id}`}>Télécharger</a><button type="button" onClick={() => rename(document)}>Renommer</button><label>Ranger<select value={document.knowledgeFolderId ?? ''} onChange={(event) => void move(document,event.target.value)}><option value="">Sans dossier</option>{folders.map((folder) => <option value={folder.id} key={folder.id}>{folder.name}</option>)}</select></label><button type="button" onClick={() => analyze(document)} disabled={busy || document.status === 'analyzing'}>{document.status === 'ready' ? 'Réanalyser' : document.status === 'failed' ? 'Réessayer' : 'Analyser'}</button><button className="danger-text" type="button" onClick={() => remove(document)}>Supprimer</button></div>
          {openId === document.id && <DocumentPagesEditor document={document} notify={notify} onSaved={load} />}
        </article>)}{!filtered.length && <div className="empty-state"><span>▤</span><h3>Aucun document ici</h3><p>Importez une source ou choisissez un autre dossier.</p></div>}</div>
      </div>
    </div>
  </section>;
}

function DocumentPagesEditor({ document,notify,onSaved }: { document:DocumentRecord;notify:(message:string)=>void;onSaved:()=>Promise<void> }) {
  const [pages,setPages] = useState<DocumentPage[]>([]); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false);
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { apiJson<{pages:DocumentPage[]}>(`/api/documents/${document.id}/pages`).then((result) => { if (active) setPages(result.pages); }).catch((error) => notify(error instanceof Error ? error.message : 'Lecture des pages impossible.')).finally(() => { if (active) setLoading(false); }); },0); return () => { active = false; window.clearTimeout(timer); }; },[document.id,notify]);
  const update = (id:string,values:Partial<DocumentPage>) => setPages((items) => items.map((page) => page.id === id ? {...page,...values} : page));
  const selectAll = (selected:boolean) => setPages((items) => items.map((page) => ({...page,selected:selected && page.readingQuality !== 'illegible'})));
  const save = async () => { setSaving(true); try { const result = await apiJson<{message:string}>(`/api/documents/${document.id}/pages`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pages:pages.map((page) => ({id:page.id,selected:page.selected,title:page.title,summary:page.summary,objectives:page.objectives,excludedInformation:page.excludedInformation,trainerNotes:page.trainerNotes,validated:true}))})}); notify(result.message); await onSaved(); } catch (error) { notify(error instanceof Error ? error.message : 'Enregistrement des pages impossible.'); } finally { setSaving(false); } };
  if (loading) return <div className="document-page-loading">Chargement de l’analyse détaillée…</div>;
  if (!pages.length) return <div className="document-page-empty"><strong>Aucune analyse page par page.</strong><p>Lancez l’analyse pour vérifier le contenu et choisir les pages utilisées par l’IA.</p></div>;
  return <section className="document-pages"><header><div><strong>Analyse pédagogique détaillée</strong><small>{pages.filter((page) => page.selected).length} page(s) sélectionnée(s) sur {pages.length}</small></div><div><button type="button" onClick={() => selectAll(true)}>Tout sélectionner</button><button type="button" onClick={() => selectAll(false)}>Tout désélectionner</button><button className="button dark" type="button" disabled={saving} onClick={save}>{saving ? 'Enregistrement…' : 'Valider les pages'}</button></div></header>{pages.map((page) => <details className={`document-page quality-${page.readingQuality} ${page.selected ? 'selected' : ''}`} key={page.id}><summary><label onClick={(event) => event.stopPropagation()}><input type="checkbox" checked={page.selected} disabled={page.readingQuality === 'illegible'} onChange={(event) => update(page.id,{selected:event.target.checked})} /><span>Page {page.pageNumber}</span></label><strong>{page.title || 'Page sans titre détecté'}</strong><small>{qualityLabel(page.readingQuality)}</small></summary><div><label>Titre repéré<input value={page.title} onChange={(event) => update(page.id,{title:event.target.value})} /></label><label>Résumé vérifiable<textarea rows={4} value={page.summary} onChange={(event) => update(page.id,{summary:event.target.value})} /></label><label>Objectifs pédagogiques<textarea rows={3} value={page.objectives.join('\n')} onChange={(event) => update(page.id,{objectives:event.target.value.split('\n').map((item) => item.trim()).filter(Boolean)})} /></label><label>Informations à exclure<textarea rows={3} value={page.excludedInformation.join('\n')} onChange={(event) => update(page.id,{excludedInformation:event.target.value.split('\n').map((item) => item.trim()).filter(Boolean)})} placeholder="Une ligne par information que l’IA ne doit pas utiliser." /></label><label>Notes du formateur<textarea rows={3} value={page.trainerNotes} onChange={(event) => update(page.id,{trainerNotes:event.target.value})} placeholder="Ajoutez une précision ou une règle interne." /></label><PageTags title="Notions" values={page.notions} /><PageTags title="Procédures" values={page.procedures} /><PageTags title="Risques" values={page.risks} />{!!page.warnings.length && <div className="page-warning"><strong>Points à vérifier</strong>{page.warnings.join(' · ')}</div>}</div></details>)}</section>;
}

function PageTags({title,values}:{title:string;values:string[]}) { if (!values.length) return null; return <div className="page-tags"><strong>{title}</strong><span>{values.join(' · ')}</span></div>; }
function StatusBadge({status}:{status:DocumentStatus}) { return <span className={`document-status ${status}`}>{({uploaded:'À analyser',validating:'Validation',extracting:'Extraction',analyzing:'Analyse en cours',indexed:'Indexé',ready:'Prêt',failed:'Échec'} as Record<DocumentStatus,string>)[status]}</span>; }
function statusCopy(status:DocumentStatus) { return status === 'ready' ? 'Document analysé et prêt à être réutilisé.' : status === 'failed' ? 'L’analyse doit être relancée.' : status === 'analyzing' ? 'Lecture visuelle des pages et indexation en cours…' : 'Import terminé. Analyse pédagogique à effectuer.'; }
function qualityLabel(value:DocumentPage['readingQuality']) { return value === 'good' ? 'Lecture fiable' : value === 'partial' ? 'Lecture partielle' : 'Illisible — écartée'; }
function formatIcon(mime:string) { if (mime === 'application/pdf') return 'PDF'; if (mime.includes('presentation') || mime.includes('powerpoint')) return 'PPT'; if (mime.includes('wordprocessing')) return 'DOC'; if (mime.startsWith('image/')) return 'IMG'; return 'TXT'; }
function formatBytes(value:number) { if (value < 1024 * 1024) return `${Math.max(1,Math.round(value / 1024))} Ko`; return `${(value / 1024 / 1024).toFixed(1)} Mo`; }
async function apiJson<T>(url:string,options?:RequestInit):Promise<T> { const response = await fetch(url,options); const payload = await response.json() as ApiEnvelope<T>; if (!payload.ok) throw new Error(payload.error.message); return payload.data; }
