/* eslint-disable @next/next/no-img-element */
'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityPlayer, type JourneyCompletion } from '@/components/activity-player';
import type { ActivityDraft } from '@/lib/activity-types';

type Item=ActivityDraft&{id:string;activityId:string;pathId:string;position:number;required:boolean;minScore:number;unlockAfterPrevious:boolean;activityStatus:string;qualityScore:number;updatedAt:number};
type Assignment={id:string;trainingId:string;trainerId:string;startsAt:number|null;dueAt:number|null;status:string;orderMode:'sequential'|'free';maxAttempts:number;resultVisible:boolean;commentsVisible:boolean;uploadAllowed:boolean;chatAllowed:boolean;voiceAllowed:boolean;voiceDurationSeconds:number;manualValidation:boolean;trainingName:string;trainingDescription:string;coverImageUrl:string|null;pathId:string|null;pathName:string|null;items:Item[]};
type Progress={id:string;assignmentId:string;activityId:string;status:string;score:number|null;maxScore:number|null;attempts:number;updatedAt:number};
type Message={id:string;authorId:string;body:string;readAt:number|null;createdAt:number};
type Evaluation={id:string;assignmentId:string;activityId:string;status:string;score:number|null;maxScore:number|null;publicComment:string;updatedAt:number};
type Submission={id:string;assignmentId:string;activityId:string|null;originalName:string;status:string;trainerComment:string;createdAt:number};
type PortalData={learner:{id:string;email:string;firstName:string|null;lastName:string|null;displayName:string|null};profile:{organization:string;groupName:string;assignedTrainerId:string|null;trainerFirstName:string|null;trainerLastName:string|null;trainerDisplayName:string|null}|null;assignments:Assignment[];progress:Progress[];evaluations:Evaluation[];submissions:Submission[];messages:Message[];notifications:Array<{id:string;title:string;body:string;readAt:number|null;createdAt:number}>};
type ApiResult<T>={ok:true;data:T}|{ok:false;error:{message:string}};

async function api<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const payload=await response.json() as ApiResult<T>;if(!payload.ok)throw new Error(payload.error.message);return payload.data;}

export function LearnerPortal({onLogout}:{onLogout:()=>Promise<void>}){
  const[data,setData]=useState<PortalData|null>(null);const[message,setMessage]=useState('');const[tab,setTab]=useState<'home'|'results'|'messages'>('home');const[selected,setSelected]=useState<string|null>(null);const[playing,setPlaying]=useState<{assignment:Assignment;index:number}|null>(null);
  const load=useCallback(async()=>{try{setData(await api<PortalData>('/api/learner/me'));}catch(error){setMessage(error instanceof Error?error.message:'Chargement impossible.');}},[]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const progressMap=useMemo(()=>new Map((data?.progress??[]).map((row)=>[`${row.assignmentId}:${row.activityId}`,row])),[data]);
  const summary=useMemo(()=>{const assignments=data?.assignments??[];const total=assignments.reduce((sum,item)=>sum+item.items.length,0);const completed=assignments.reduce((sum,item)=>sum+item.items.filter((activity)=>['completed','validated'].includes(progressMap.get(`${item.id}:${activity.activityId}`)?.status??'')).length,0);return{paths:assignments.length,total,completed,remaining:Math.max(0,total-completed),percent:total?Math.round(completed/total*100):0};},[data,progressMap]);
  const openActivity=async(assignment:Assignment,index:number)=>{const item=assignment.items[index];if(!item)return;try{await api('/api/learner/progress',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId:assignment.id,activityId:item.activityId,status:'in_progress'})});setPlaying({assignment,index});await load();}catch(error){setMessage(error instanceof Error?error.message:'Cette activité ne peut pas encore être ouverte.');}};
  const complete=async(result:JourneyCompletion={})=>{if(!playing)return;const item=playing.assignment.items[playing.index];const response=await api<{message:string}>('/api/learner/progress',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId:playing.assignment.id,activityId:item.activityId,status:'completed',...result})});setMessage(response.message);await load();};
  if(!data)return <main className="learner-portal loading"><div className="learner-loading"><span className="brand-mark">P</span><strong>Ouverture de votre espace apprenant…</strong>{message&&<p>{message}</p>}</div></main>;
  const current=data.assignments.find((item)=>item.id===selected)??null;const trainer=[data.profile?.trainerFirstName,data.profile?.trainerLastName].filter(Boolean).join(' ')||data.profile?.trainerDisplayName||'Votre formateur';
  return <main className="learner-portal"><aside className="learner-sidebar"><button className="brand brand-button" onClick={()=>{setSelected(null);setTab('home')}}><span className="brand-mark">P</span><span>Progressed<br/><strong>Pédago</strong></span></button><nav><button className={tab==='home'?'active':''} onClick={()=>{setTab('home');setSelected(null)}}>⌂ Mon accueil</button><button className={tab==='results'?'active':''} onClick={()=>{setTab('results');setSelected(null)}}>▥ Mes résultats</button><button className={tab==='messages'?'active':''} onClick={()=>{setTab('messages');setSelected(null);void api('/api/learner/me',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read_messages'})}).then(()=>load())}}>✉ Mon formateur <i>{data.messages.filter((item)=>item.authorId!==data.learner.id&&item.readAt==null).length||''}</i></button></nav><div className="learner-profile"><span>{(data.learner.firstName?.[0]??'A')+(data.learner.lastName?.[0]??'')}</span><div><strong>{data.learner.displayName}</strong><small>{data.profile?.groupName||'Apprenant'}</small></div><button onClick={()=>void onLogout()} aria-label="Se déconnecter">↪</button></div></aside><section className="learner-workspace">
    <header className="learner-header"><div><p className="overline">Espace apprenant</p><h1>Bonjour {data.learner.firstName||'à vous'}.</h1><p>{current?'Avancez étape par étape dans votre parcours.':'Retrouvez uniquement les parcours et activités qui vous sont attribués.'}</p></div><div className="learner-trainer"><span>Formateur référent</span><strong>{trainer}</strong></div></header>{message&&<div className="learner-flash" role="status">{message}<button onClick={()=>setMessage('')}>×</button></div>}
    {tab==='home'&&!current&&<><section className="learner-summary"><article><span>Parcours attribués</span><strong>{summary.paths}</strong></article><article><span>Activités terminées</span><strong>{summary.completed}</strong></article><article><span>Activités restantes</span><strong>{summary.remaining}</strong></article><article className="progress"><span>Progression générale</span><strong>{summary.percent}%</strong><i><em style={{width:`${summary.percent}%`}}/></i></article></section><section className="learner-paths"><div><p className="overline">Mes parcours</p><h2>À faire et en cours</h2></div>{data.assignments.length?data.assignments.map((assignment)=>{const done=assignment.items.filter((item)=>['completed','validated'].includes(progressMap.get(`${assignment.id}:${item.activityId}`)?.status??'')).length;const percent=assignment.items.length?Math.round(done/assignment.items.length*100):0;const next=assignment.items.find((item)=>!['completed','validated'].includes(progressMap.get(`${assignment.id}:${item.activityId}`)?.status??''));return <article className="learner-path-card" key={assignment.id}><div className="learner-path-cover">{assignment.coverImageUrl?<img src={assignment.coverImageUrl} alt=""/>:<span>▤</span>}</div><div><span className={`status-pill ${percent===100?'active':'pending'}`}>{percent===100?'Terminé':percent?'En cours':'À faire'}</span><h3>{assignment.trainingName}</h3><p>{assignment.trainingDescription||`${assignment.items.length} activité(s) guidée(s)`}</p><dl><div><dt>Progression</dt><dd>{done}/{assignment.items.length}</dd></div><div><dt>Prochaine activité</dt><dd>{next?.title??'Parcours terminé'}</dd></div>{assignment.dueAt&&<div><dt>Date limite</dt><dd>{new Date(assignment.dueAt*1000).toLocaleDateString('fr-FR')}</dd></div>}</dl><div className="path-progress"><i><em style={{width:`${percent}%`}}/></i><b>{percent}%</b></div><button className="button dark" onClick={()=>setSelected(assignment.id)}>Continuer mon parcours →</button></div></article>}) : <div className="learner-empty"><span>✓</span><h3>Aucun parcours à faire pour le moment.</h3><p>Votre formateur vous préviendra dès qu’un nouveau parcours sera disponible.</p></div>}</section></>}
    {tab==='home'&&current&&(
      <PathDetail assignment={current} progressMap={progressMap} onBack={()=>setSelected(null)} onOpen={(index)=>void openActivity(current,index)} onRefresh={load} onMessage={setMessage}/>
    )}
    {tab==='results'&&(
      <ResultsPanel evaluations={data.evaluations} submissions={data.submissions} assignments={data.assignments}/>
    )}
    {tab==='messages'&&<MessagesPanel data={data} trainer={trainer} onSent={async(text)=>{const response=await api<{message:string}>('/api/learner/me',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'message',message:text})});setMessage(response.message);await load();}}/>}
  </section>{playing&&(()=>{const activity=playing.assignment.items[playing.index];const progress=progressMap.get(`${playing.assignment.id}:${activity.activityId}`);return <ActivityPlayer activity={activity} onClose={()=>setPlaying(null)} journey={{name:playing.assignment.trainingName,index:playing.index,total:playing.assignment.items.length,trainingId:playing.assignment.trainingId,pathId:activity.pathId,pathItemId:activity.id,onPrevious:playing.index?()=>void openActivity(playing.assignment,playing.index-1):undefined,onNext:playing.index<playing.assignment.items.length-1?()=>void openActivity(playing.assignment,playing.index+1):undefined,onComplete:complete,completed:['completed','validated','submitted'].includes(progress?.status??'')}}/>})()}</main>;
}

function PathDetail({assignment,progressMap,onBack,onOpen,onRefresh,onMessage}:{assignment:Assignment;progressMap:Map<string,Progress>;onBack:()=>void;onOpen:(index:number)=>void;onRefresh:()=>Promise<void>;onMessage:(value:string)=>void}){const[busy,setBusy]=useState(false);const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget);form.set('assignmentId',assignment.id);const response=await fetch('/api/learner/submissions',{method:'POST',body:form});const payload=await response.json() as ApiResult<{message:string}>;if(!payload.ok)throw new Error(payload.error.message);onMessage(payload.data.message);event.currentTarget.reset();await onRefresh();}catch(error){onMessage(error instanceof Error?error.message:'Envoi impossible.');}finally{setBusy(false);}};return <section className="learner-path-detail"><button className="back-button" onClick={onBack}>← Tous mes parcours</button><div className="learner-path-title"><div><p className="overline">Parcours attribué</p><h2>{assignment.trainingName}</h2><p>{assignment.trainingDescription}</p></div><span>{assignment.orderMode==='sequential'?'Ordre guidé':'Ordre libre'}</span></div><ol className="learner-timeline">{assignment.items.map((item,index)=>{const progress=progressMap.get(`${assignment.id}:${item.activityId}`);const previous=index?progressMap.get(`${assignment.id}:${assignment.items[index-1].activityId}`):null;const locked=assignment.orderMode==='sequential'&&index>0&&!['completed','validated'].includes(previous?.status??'');const status=locked?'locked':progress?.status??(index===0||assignment.orderMode==='free'?'available':'locked');return <li className={status} key={item.id}><span>{locked?'🔒':['completed','validated'].includes(status)?'✓':index+1}</span><div><small>{statusLabel(status)}</small><strong>{item.title}</strong><p>{item.instructions}</p><em>{item.durationMinutes} min{item.minScore?` · minimum ${item.minScore}%`:''}</em></div><button className="button light" disabled={locked} onClick={()=>onOpen(index)}>{['completed','validated'].includes(status)?'Revoir':'Commencer'}</button></li>})}</ol>{assignment.uploadAllowed&&<form className="learner-upload" onSubmit={upload}><div><strong>Envoyer une production</strong><p>PDF, Word, Excel, PowerPoint, image, audio ou vidéo · 25 Mo maximum.</p></div><select name="activityId" defaultValue=""><option value="">Production générale du parcours</option>{assignment.items.map((item)=><option key={item.id} value={item.activityId}>{item.title}</option>)}</select><input name="file" type="file" accept=".pdf,.docx,.xlsx,.pptx,.png,.jpg,.jpeg,.mp3,.wav,.mp4" required/><textarea name="comment" placeholder="Commentaire facultatif pour votre formateur"/><button className="button dark" disabled={busy}>{busy?'Envoi sécurisé…':'Envoyer au formateur'}</button></form>}</section>}

function ResultsPanel({evaluations,submissions,assignments}:{evaluations:Evaluation[];submissions:Submission[];assignments:Assignment[]}){return <section className="learner-results-panel"><p className="overline">Mon suivi</p><h2>Résultats et productions</h2><div className="learner-result-grid"><section><h3>Corrections du formateur</h3>{evaluations.length?evaluations.map((item)=><article key={item.id}><span className={`status-pill ${item.status==='validated'?'active':'pending'}`}>{statusLabel(item.status)}</span><strong>{assignments.find((a)=>a.id===item.assignmentId)?.items.find((a)=>a.activityId===item.activityId)?.title??'Activité'}</strong>{item.score!=null&&item.maxScore&&<b>{item.score}/{item.maxScore}</b>}{item.publicComment&&<p>{item.publicComment}</p>}</article>):<p>Aucune correction disponible.</p>}</section><section><h3>Mes productions</h3>{submissions.length?submissions.map((item)=><article key={item.id}><span className={`status-pill ${item.status==='validated'?'active':'pending'}`}>{statusLabel(item.status)}</span><a href={`/api/learner/submissions/${item.id}`}>{item.originalName}</a>{item.trainerComment&&<p>{item.trainerComment}</p>}</article>):<p>Aucune production envoyée.</p>}</section></div></section>}

function MessagesPanel({data,trainer,onSent}:{data:PortalData;trainer:string;onSent:(text:string)=>Promise<void>}){const[text,setText]=useState('');const[busy,setBusy]=useState(false);return <section className="learner-messages"><p className="overline">Messagerie privée</p><h2>Échanger avec {trainer}</h2><p>Cette conversation est uniquement visible par vous et votre formateur référent.</p><div>{data.messages.length?data.messages.map((item)=><article className={item.authorId===data.learner.id?'mine':''} key={item.id}><small>{item.authorId===data.learner.id?'Vous':trainer} · {new Date(item.createdAt*1000).toLocaleString('fr-FR')}</small><p>{item.body}</p></article>):<p>Aucun message pour le moment.</p>}</div><form onSubmit={async(event)=>{event.preventDefault();if(!text.trim())return;setBusy(true);try{await onSent(text);setText('');}finally{setBusy(false);}}}><textarea value={text} onChange={(event)=>setText(event.target.value)} placeholder="Écrire un message à mon formateur…"/><button className="button dark" disabled={busy||!text.trim()}>Envoyer</button></form></section>}

function statusLabel(status:string){return({not_started:'Non commencée',available:'Disponible',in_progress:'En cours',submitted:'Remise au formateur',reviewing:'En attente de correction',validated:'Corrigée',completed:'Terminée',retry:'À revoir',locked:'Verrouillée'} as Record<string,string>)[status]??status;}
