'use client';

import { FormEvent, useEffect, useState } from 'react';
import { BrandLockup } from '@/components/brand-logo';

type Invitation = { firstName:string; lastName:string; email:string; organization:string; groupName:string; expiresAt:number; existingAccount:boolean; trainings:Array<{id:string;name:string}> };
type ApiResult<T> = { ok:true; data:T } | { ok:false; error:{message:string} };

export function LearnerInvite({ token }: { token:string }) {
  const [invitation,setInvitation]=useState<Invitation|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch(`/api/learner/invitations/${encodeURIComponent(token)}`).then(async(response)=>{const payload=await response.json() as ApiResult<{invitation:Invitation}>;if(!payload.ok)throw new Error(payload.error.message);setInvitation(payload.data.invitation);}).catch((error)=>setMessage(error instanceof Error?error.message:'Invitation indisponible.'));},[token]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setMessage('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch(`/api/learner/invitations/${encodeURIComponent(token)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,privacyAccepted:data.privacyAccepted==='on'})});const payload=await response.json() as ApiResult<{message:string}>;if(!payload.ok)throw new Error(payload.error.message);window.location.assign('/');}catch(error){setMessage(error instanceof Error?error.message:'Activation impossible.');setBusy(false);}};
  return <main className="invite-page"><section className="invite-card"><BrandLockup priority/><p className="overline">Espace apprenant sécurisé</p><h1>{invitation?`Bienvenue ${invitation.firstName}.`:'Vérification de votre invitation…'}</h1>{invitation&&<><p>Confirmez votre accès à Progressed Pédago. Vous verrez uniquement les parcours qui vous sont attribués.</p><dl className="invite-summary"><div><dt>Compte</dt><dd>{invitation.email}</dd></div>{invitation.organization&&<div><dt>Organisme</dt><dd>{invitation.organization}</dd></div>}{invitation.groupName&&<div><dt>Groupe</dt><dd>{invitation.groupName}</dd></div>}<div><dt>Parcours</dt><dd>{invitation.trainings.map((item)=>item.name).join(', ')||'Aucun parcours initial'}</dd></div></dl><form onSubmit={submit}><label>{invitation.existingAccount?'Mot de passe actuel':'Créer un mot de passe'}<input name="password" type="password" autoComplete={invitation.existingAccount?'current-password':'new-password'} required/></label>{!invitation.existingAccount&&<small>12 caractères minimum, avec majuscule, minuscule, chiffre et caractère spécial.</small>}<label className="consent-row"><input name="privacyAccepted" type="checkbox" required/><span>J’accepte que mes données nécessaires au suivi pédagogique (progression, résultats, productions et échanges) soient conservées dans mon espace.</span></label>{message&&<p className="form-message" role="status">{message}</p>}<button className="button dark full" disabled={busy} type="submit">{busy?'Ouverture sécurisée…':'Accéder à mon espace'}</button></form></>}{!invitation&&message&&<p className="form-message" role="alert">{message}</p>}</section></main>;
}
