'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityPlayer, type JourneyCompletion } from '@/components/activity-player';
import { ACTIVITY_TYPES, type ActivityType } from '@/lib/activity-types';

type ProgressState={pathItemId:string;status:'not_started'|'in_progress'|'completed'|'passed'|'retry';score:number|null;maxScore:number|null;attempts:number};
type PathActivity={pathItemId:string;position:number;required:boolean;minScore:number;unlockAfterPrevious:boolean;activityId:string;type:string;title:string;theme:string;audience:string|null;level:string;objectives:string[];durationMinutes:number;instructions:string;content:Record<string,unknown>;explanation:string;sources:Array<{title:string;organization?:string;url:string;usedFor?:string}>;status:string};
type ExternalResource={id:string;name:string;url:string;category:string;provider:string;resourceType:string;activityId:string|null;placement:string;required:boolean;openMode:string;embedUrl:string|null;thumbnailUrl:string|null};
type JourneyData={share:{shortCode:string;mode:'classroom'|'home';identityMode:'name'|'pseudonym'|'learner_code'|'anonymous';expiresAt:number|null;sessionOpen:boolean};training:{id:string;name:string;description:string;audience:string;level:string;durationMinutes:number;coverImageUrl:string|null};path:{id:string;name:string;items:PathActivity[]};resources:ExternalResource[];participant:{id:string;displayName:string;progressPercent:number;lastPathItemId:string|null;progress:ProgressState[]}|null};
type ApiResult<T>={ok:true;data:T}|{ok:false;error:{message:string;code:string}};

async function publicApi<T>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const payload=await response.json() as ApiResult<T>;if(!payload.ok)throw new Error(payload.error.message);return payload.data;}

export function LearnerJourney({token}:{token:string}){
  const endpoint=`/api/public/shares/${encodeURIComponent(token)}`;const[data,setData]=useState<JourneyData|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[activeIndex,setActiveIndex]=useState<number|null>(null);const[resumeCode,setResumeCode]=useState('');const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{try{const next=await publicApi<JourneyData>(endpoint);setData(next);setError('');if(next.participant)setActiveIndex((current)=>current??Math.max(0,next.path.items.findIndex((item)=>item.pathItemId===next.participant?.lastPathItemId)));}catch(reason){setError(reason instanceof Error?reason.message:'Ce parcours est momentanément indisponible.');}finally{setLoading(false);}},[endpoint]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const participant=data?.participant;const items=data?.path.items??[];const current=activeIndex===null?null:items[activeIndex]??null;
  const stateByItem=useMemo(()=>new Map((participant?.progress??[]).map((item)=>[item.pathItemId,item])),[participant?.progress]);
  const isCompleted=(item:PathActivity)=>{const state=stateByItem.get(item.pathItemId);return state?.status==='completed'||state?.status==='passed';};
  const isUnlocked=(index:number)=>{const item=items[index];if(!item||!item.unlockAfterPrevious||index===0)return true;const previous=items[index-1];const state=stateByItem.get(previous.pathItemId);const percentage=state?.score!=null&&state.maxScore?Math.round(state.score/state.maxScore*100):isCompleted(previous)?100:0;return isCompleted(previous)&&percentage>=previous.minScore;};
  const openStep=async(index:number)=>{if(!isUnlocked(index)){setNotice('Cette étape sera disponible après la réussite de l’étape précédente.');return;}setActiveIndex(index);setNotice('');try{await publicApi(`${endpoint}/progress`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pathItemId:items[index].pathItemId,status:'in_progress'})});}catch{/* L’ouverture reste possible si la connexion a brièvement été interrompue. */}};
  const complete=async(result?:JourneyCompletion)=>{if(!current||busy)return;setBusy(true);try{const update=await publicApi<{progressPercent:number;status:'completed'|'passed'|'retry';message:string}>(`${endpoint}/progress`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pathItemId:current.pathItemId,status:result?.score!=null&&result.maxScore?Math.round(result.score/result.maxScore*100)>=current.minScore?'passed':'retry':'completed',...result})});setNotice(update.message);await load();const nextIndex=(activeIndex??0)+1;if(nextIndex<items.length&&update.status!=='retry')setActiveIndex(nextIndex);else if(update.progressPercent===100)setActiveIndex(null);}catch(reason){setNotice(reason instanceof Error?reason.message:'Progression non enregistrée.');}finally{setBusy(false);}};
  if(loading)return <main className="learner-loading"><span>Progressed Pédago</span><strong>Préparation de votre parcours…</strong></main>;
  if(error||!data)return <main className="learner-error"><span>!</span><h1>Accès au parcours impossible</h1><p>{error}</p><small>Demandez au formateur un nouveau lien si nécessaire.</small></main>;
  if(!participant)return <LearnerEntry data={data} endpoint={endpoint} busy={busy} setBusy={setBusy} onStarted={async(code)=>{setResumeCode(code);await load();}}/>;
  const timeline=<JourneyTimeline data={data} activeIndex={activeIndex??0} stateByItem={stateByItem} isUnlocked={isUnlocked} onOpen={(index)=>void openStep(index)} onFinish={()=>setActiveIndex(null)}/>;
  const resources=data.resources.filter((resource)=>!resource.activityId||resource.activityId===current?.activityId);
  if(current)return <><ActivityPlayer key={current.pathItemId} activity={{...current,id:current.activityId,type:current.type as ActivityType,audience:current.audience??undefined,level:current.level as 'debutant'|'intermediaire'|'avance'}} onClose={()=>setActiveIndex(null)} journey={{name:data.training.name,index:activeIndex??0,total:items.length,trainingId:data.training.id,pathId:data.path.id,onPrevious:(activeIndex??0)>0&&isUnlocked((activeIndex??0)-1)?()=>void openStep((activeIndex??0)-1):undefined,onNext:(activeIndex??0)<items.length-1&&isUnlocked((activeIndex??0)+1)?()=>void openStep((activeIndex??0)+1):undefined,onComplete:complete,completed:isCompleted(current),timeline,resourcePanel:<JourneyResources resources={resources}/>}}/>{notice&&<div className="learner-notice" role="status">{busy?'Enregistrement…':notice}</div>}</>;
  const resumeIndex=Math.max(0,items.findIndex((item,index)=>!isCompleted(item)&&isUnlocked(index)));
  return <main className="learner-home"><section className="learner-welcome"><p className="overline">Parcours apprenant</p><h1>{data.training.name}</h1><p>{data.training.description}</p><div><span>{participant.displayName}</span><strong>{participant.progressPercent}% terminé</strong></div>{participant.progressPercent===100?<div className="success-banner">✓ Parcours terminé. Vos résultats ont été transmis au formateur.</div>:<button className="button dark" type="button" onClick={()=>void openStep(resumeIndex)}>{participant.progressPercent?'Reprendre mon parcours':'Commencer le parcours'} →</button>}{resumeCode&&<aside><strong>Votre code de reprise</strong><code>{resumeCode}</code><p>Notez-le : il permet de retrouver votre avancement depuis un autre navigateur.</p></aside>}</section>{timeline}</main>;
}

function LearnerEntry({data,endpoint,busy,setBusy,onStarted}:{data:JourneyData;endpoint:string;busy:boolean;setBusy:(value:boolean)=>void;onStarted:(resumeCode:string)=>Promise<void>}){const[resume,setResume]=useState(false);const[message,setMessage]=useState('');const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget);try{const result=await publicApi<{resumeCode:string|null;message:string}>(`${endpoint}/participants`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});await onStarted(result.resumeCode??'');}catch(reason){setMessage(reason instanceof Error?reason.message:'Entrée impossible.');}finally{setBusy(false);}};return <main className="learner-entry"><section><div className="learner-entry-brand"><span>P</span><strong>Progressed<br/>Pédago</strong></div><p className="overline">Invitation à une formation</p><h1>{data.training.name}</h1><p>{data.training.description||'Votre formateur a préparé un parcours progressif et interactif.'}</p><div className="learner-entry-facts"><span>{data.path.items.length} étapes</span><span>{data.training.durationMinutes} min</span><span>{data.share.mode==='classroom'?'Session en salle':'Travail à domicile'}</span></div><form onSubmit={submit}><h2>{resume?'Reprendre un parcours':'Accéder sans créer de compte'}</h2>{resume?<label>Code personnel de reprise<input name="resumeCode" required autoComplete="one-time-code" placeholder="Ex. A7K9P2QX"/></label>:<IdentityFields mode={data.share.identityMode}/>}<button className="button dark" disabled={busy}>{busy?'Ouverture…':resume?'Reprendre mon parcours':'Entrer dans la formation'}</button>{message&&<p role="alert">{message}</p>}</form><button className="learner-resume-switch" type="button" onClick={()=>setResume((value)=>!value)}>{resume?'Je commence pour la première fois':'J’ai déjà un code de reprise'}</button><small>Aucune adresse électronique ni aucun mot de passe ne sont demandés.</small></section></main>;}
function IdentityFields({mode}:{mode:JourneyData['share']['identityMode']}){if(mode==='anonymous')return <p className="learner-anonymous">Vous participerez de manière anonyme.</p>;if(mode==='pseudonym')return <label>Pseudonyme<input name="pseudonym" required maxLength={100}/></label>;if(mode==='learner_code')return <label>Code apprenant<input name="learnerCode" required maxLength={100}/></label>;return <div className="form-row two"><label>Prénom<input name="firstName" required maxLength={80}/></label><label>Nom<input name="lastName" required maxLength={80}/></label></div>;}

function JourneyTimeline({data,activeIndex,stateByItem,isUnlocked,onOpen,onFinish}:{data:JourneyData;activeIndex:number;stateByItem:Map<string,ProgressState>;isUnlocked:(index:number)=>boolean;onOpen:(index:number)=>void;onFinish:()=>void}){const[collapsed,setCollapsed]=useState(false);useEffect(()=>{const timer=window.setTimeout(()=>{if(window.matchMedia('(max-width: 820px)').matches)setCollapsed(true);},0);return()=>window.clearTimeout(timer);},[]);const completed=data.path.items.filter((item)=>{const status=stateByItem.get(item.pathItemId)?.status;return status==='completed'||status==='passed';}).length;const finished=(data.participant?.progressPercent??0)===100;return <aside className={`journey-timeline ${collapsed?'collapsed':''}`} aria-label="Timeline du parcours"><header><button type="button" onClick={()=>setCollapsed((value)=>!value)} aria-label={collapsed?'Afficher le parcours':'Réduire le parcours'}><b aria-hidden="true">{collapsed?'⌄':'›'}</b><span className="journey-toggle-label">{collapsed?'Voir mon parcours':'Masquer le parcours'}</span></button><div><small>Progression</small><strong>{data.participant?.progressPercent??0}%</strong><span><i style={{width:`${data.participant?.progressPercent??0}%`}}/></span><p>{completed} activité{completed>1?'s':''} terminée{completed>1?'s':''} sur {data.path.items.length}</p></div></header>{!collapsed&&<><nav>{data.path.items.map((item,index)=>{const state=stateByItem.get(item.pathItemId);const unlocked=isUnlocked(index);const completedState=state?.status==='completed'||state?.status==='passed';const retry=state?.status==='retry';return <button type="button" className={`${index===activeIndex?'current':''} ${completedState?'done':''} ${!unlocked?'locked':''} ${retry?'retry':''}`} disabled={!unlocked} onClick={()=>onOpen(index)} key={item.pathItemId}><span>{completedState?'✓':!unlocked?'⌁':index+1}</span><div><strong>{item.title}</strong><small>{ACTIVITY_TYPES.find(([type])=>type===item.type)?.[1]??item.type} · {item.durationMinutes} min</small><em>{item.required?'Obligatoire':'Facultative'}{retry?' · À reprendre':''}</em></div></button>;})}</nav><footer>{finished&&<button className="journey-finish-button" type="button" onClick={onFinish}>Terminer le parcours ✓</button>}<button type="button" onClick={()=>window.location.assign('/')}>← Retour aux formations</button></footer></>}</aside>;}

function JourneyResources({resources}:{resources:ExternalResource[]}){if(!resources.length)return null;return <section className="journey-resource-panel"><div><small>Ressources de cette étape</small><strong>{resources.length} support{resources.length>1?'s':''}</strong></div>{resources.map((resource)=><article key={resource.id}><span>{resource.category}</span><div><strong>{resource.name}</strong><small>{placementLabel(resource.placement)} · {resource.required?'Obligatoire':'Facultative'}</small></div><a href={resource.url} target="_blank" rel="noreferrer">Ouvrir ↗</a>{resource.openMode==='site'&&resource.embedUrl&&<iframe src={resource.embedUrl} title={resource.name} loading="lazy" sandbox="allow-scripts allow-same-origin allow-popups allow-forms" referrerPolicy="strict-origin-when-cross-origin"/>}</article>)}</section>;}
function placementLabel(value:string){return ({before:'Avant l’exercice',after:'Après l’exercice',course:'Cours',instructions:'Consigne',help:'Aide'} as Record<string,string>)[value]??'Ressource';}
