import { env } from '@/lib/runtime-env';
import { and, desc, eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { learnerAssignments, learnerNotifications, learnerSubmissions, learningPathItems, learningPaths } from '@/db/schema';
import { audit, requireLearner } from '@/lib/auth';
import { AppError, assertSameOrigin, jsonError, jsonOk } from '@/lib/http';
import { getActiveAssignment } from '@/lib/learner-access';
import { MAX_LEARNER_FILE_BYTES,safeFileName,validateLearnerFile } from '@/lib/learner-files';

export async function GET(){try{const learner=await requireLearner();const submissions=await getDb().select({id:learnerSubmissions.id,assignmentId:learnerSubmissions.assignmentId,activityId:learnerSubmissions.activityId,originalName:learnerSubmissions.originalName,mimeType:learnerSubmissions.mimeType,sizeBytes:learnerSubmissions.sizeBytes,status:learnerSubmissions.status,learnerComment:learnerSubmissions.learnerComment,trainerComment:learnerSubmissions.trainerComment,createdAt:learnerSubmissions.createdAt,updatedAt:learnerSubmissions.updatedAt}).from(learnerSubmissions).where(eq(learnerSubmissions.learnerId,learner.id)).orderBy(desc(learnerSubmissions.createdAt));return jsonOk({submissions});}catch(error){return jsonError(error);}}

export async function POST(request:Request){try{assertSameOrigin(request);const learner=await requireLearner();const declared=Number(request.headers.get('content-length')??0);if(declared>MAX_LEARNER_FILE_BYTES+1_000_000)throw new AppError(413,'Le fichier doit peser moins de 25 Mo.','FILE_TOO_LARGE');const form=await request.formData();const assignmentId=String(form.get('assignmentId')??'');const activityId=String(form.get('activityId')??'')||null;const comment=String(form.get('comment')??'').trim().slice(0,2000);const file=form.get('file');if(!(file instanceof File))throw new AppError(400,'Choisissez un fichier à envoyer.','FILE_REQUIRED');const assignment=(await getDb().select().from(learnerAssignments).where(and(eq(learnerAssignments.id,assignmentId),eq(learnerAssignments.learnerId,learner.id))).limit(1))[0];if(!assignment)throw new AppError(404,'Ce parcours est introuvable.','ASSIGNMENT_NOT_FOUND');await getActiveAssignment(learner.id,assignment.trainingId);if(!assignment.uploadAllowed)throw new AppError(403,'Le dépôt de fichiers n’est pas autorisé pour ce parcours.','UPLOAD_DISABLED');if(activityId){const item=(await getDb().select({id:learningPathItems.id}).from(learningPaths).innerJoin(learningPathItems,eq(learningPathItems.pathId,learningPaths.id)).where(and(eq(learningPaths.trainingId,assignment.trainingId),eq(learningPathItems.activityId,activityId))).limit(1))[0];if(!item)throw new AppError(403,'Cette activité ne fait pas partie de votre parcours.','ACTIVITY_NOT_ASSIGNED');}const bytes=new Uint8Array(await file.arrayBuffer());const validated=validateLearnerFile(file,bytes);const id=crypto.randomUUID();const objectKey=`learner-submissions/${learner.id}/${assignmentId}/${id}-${safeFileName(file.name)}`;await env.FILES.put(objectKey,bytes,{httpMetadata:{contentType:validated.mimeType}});try{await getDb().batch([getDb().insert(learnerSubmissions).values({id,assignmentId,learnerId:learner.id,activityId,objectKey,originalName:file.name.slice(0,180),mimeType:validated.mimeType,sizeBytes:file.size,learnerComment:comment}),getDb().insert(learnerNotifications).values({id:crypto.randomUUID(),userId:assignment.trainerId,kind:'submission',title:'Nouvelle production déposée',body:`${learner.displayName??learner.email} a envoyé ${file.name.slice(0,100)}.`,link:'/?view=learners'})]);}catch(error){await env.FILES.delete(objectKey);throw error;}await audit(learner.id,'learner.submission_uploaded','learner_submission',id,{assignmentId,activityId,mimeType:validated.mimeType,size:file.size},request);return jsonOk({id,message:'Votre production a été transmise au formateur.'},201);}catch(error){return jsonError(error);}}
