import { getDb } from '@/db';
import { salesLeads } from '@/db/schema';
import { audit } from '@/lib/auth';
import { AppError, assertSameOrigin, jsonError, jsonOk, readJson } from '@/lib/http';
import { sendTransactionalEmail } from '@/lib/notifications';
import { assertPublicSubmissionLimit, cleanSupportEmail, cleanText, supportAdminEmail, uniqueReference } from '@/lib/support';

export async function POST(request:Request){try{assertSameOrigin(request);await assertPublicSubmissionLimit(request,'sales');const body=await readJson(request,30_000);if(body.consent!==true)throw new AppError(400,'Votre accord est nécessaire pour traiter cette demande.','CONSENT_REQUIRED');const now=Math.floor(Date.now()/1000);const id=crypto.randomUUID();const reference=uniqueReference('COM');const email=cleanSupportEmail(body.email);const firstName=cleanText(body.firstName,80,'Le prénom');const lastName=cleanText(body.lastName,80,'Le nom');const plan=['essential','coach','intensive','undecided'].includes(String(body.planInterest))?String(body.planInterest) as 'essential'|'coach'|'intensive'|'undecided':'undecided';await getDb().insert(salesLeads).values({id,reference,firstName,lastName,organization:cleanText(body.organization,160,'L’organisme'),email,phone:cleanText(body.phone,40,'Le téléphone',false),trainerCount:bounded(body.trainerCount),learnerCount:bounded(body.learnerCount),primaryNeed:cleanText(body.primaryNeed,2_000,'Le besoin principal'),planInterest:plan,wantsDemo:body.wantsDemo===true,wantsQuote:body.wantsQuote===true,wantsCallback:body.wantsCallback===true,preferredTime:cleanText(body.preferredTime,180,'Le créneau',false),message:cleanText(body.message,4_000,'Le message',false),consentedAt:now,createdAt:now,updatedAt:now});await audit(null,'sales.lead_created','sales_lead',id,{reference,plan},request);const admin=supportAdminEmail();if(admin)await sendTransactionalEmail({to:admin,subject:`[${reference}] Nouvelle demande commerciale`,text:`${firstName} ${lastName} · ${body.organization}\n${email}\nFormule envisagée : ${plan}\n\nConsultez l’espace Administration.`});await sendTransactionalEmail({to:email,subject:`Votre demande ${reference} est enregistrée`,text:`Bonjour ${firstName},\n\nVotre demande commerciale a bien été enregistrée sous la référence ${reference}. Nous reviendrons vers vous selon les coordonnées indiquées.`});return jsonOk({reference,message:'Votre demande commerciale a bien été enregistrée.'},201)}catch(error){return jsonError(error)}}
function bounded(value:unknown):number{const number=Math.round(Number(value)||0);return Math.min(100_000,Math.max(0,number))}
